import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// In-memory store for Legacy API publications (simulating external CRM/ERP integration)
interface LegacyPublicationInput {
  token: string;
  processNumber: string;
  title: string;
  content: string;
  source?: string;
  subpoenaDate?: string;
}

let legacyPublicationsPool: any[] = [
  {
    id: "leg-1",
    processNumber: "1002345-67.2026.8.26.0100",
    title: "Intimação para réplica - Processo Cível",
    content: "Fica o autor intimado para manifestar-se sobre a contestação apresentada pelo réu no prazo legal de 15 dias úteis.",
    source: "legacy_api",
    category: "prazo",
    urgencyLevel: "media",
    subpoenaDate: new Date().toISOString(),
    deadlineDays: 15,
    dueDate: calculateBusinessDaysDate(new Date(), 15),
    actionRequired: "Elaborar réplica à contestação contestando as preliminares e o mérito alegado pelo réu.",
    status: "pendente",
    createdAt: new Date().toISOString()
  }
];

// In-memory store for API Tokens generated by users
let validTokens: string[] = ["BOSS_LEGACY_INTEGRATION_TOKEN_DEFAULT"];

// Helper to calculate business days (skips Saturday & Sunday)
function calculateBusinessDaysDate(startDate: Date, days: number): string {
  let resultDate = new Date(startDate);
  let count = 0;
  while (count < days) {
    resultDate.setDate(resultDate.getDate() + 1);
    const dayOfWeek = resultDate.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) { // 0 = Sunday, 6 = Saturday
      count++;
    }
  }
  return resultDate.toISOString();
}

// 1. API: AI Analyzer for manual copy-pasted publications
app.post("/api/analyze-publication", async (req, res) => {
  const { content, subpoenaDate } = req.body;

  if (!content) {
    return res.status(400).json({ error: "O conteúdo da publicação é obrigatório." });
  }

  const dateToUse = subpoenaDate ? new Date(subpoenaDate) : new Date();

  try {
    const prompt = `Analise o texto de intimação/publicação jurídica abaixo e retorne um objeto JSON contendo as informações extraídas.
    Siga estritamente esta estrutura JSON:
    {
      "processNumber": "Número do processo no padrão CNJ (ex: 0000000-00.0000.0.00.0000). Se não encontrar, tente identificar um formato similar ou deixe vazio",
      "title": "Um título curto e claro em português explicando o assunto (ex: 'Apresentar réplica à contestação')",
      "category": "Escolha uma destas opções exatas: 'urgente' (prazos fatais de 1 a 3 dias ou liminares), 'prazo' (outros prazos normais), 'informativo' (sem prazo, apenas ciência), 'audiencia' (marcação de audiência/julgamento)",
      "urgencyLevel": "Escolha uma destas opções exatas: 'alta' (prazos curtos ou liminares), 'media' (prazos normais de 15 dias), 'baixa' (ciência ou prazos longos)",
      "deadlineDays": "Número inteiro representando o prazo em dias (ex: 15). Se não houver prazo claro, retorne 0",
      "actionRequired": "Instruções claras e objetivas em português para o advogado tomar as providências adequadas"
    }

    Texto da publicação:
    "${content}"`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("Sem resposta do modelo Gemini.");
    }

    const parsed = JSON.parse(responseText.trim());
    
    // Calculate due date based on calculated business days
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(dateToUse, deadlineDays)
      : dateToUse.toISOString();

    return res.json({
      processNumber: parsed.processNumber || "Não identificado",
      title: parsed.title || "Publicação Jurídica",
      category: parsed.category || "informativo",
      urgencyLevel: parsed.urgencyLevel || "baixa",
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar teor da publicação.",
      content: content,
      subpoenaDate: dateToUse.toISOString()
    });

  } catch (error: any) {
    console.error("Erro na análise do Gemini:", error);
    return res.status(500).json({ error: "Erro ao processar análise da publicação com IA: " + error.message });
  }
});

// 2. API: Gmail Sync (queries Gmail using OAuth Access Token passed by frontend)
app.post("/api/gmail-sync", async (req, res) => {
  const { accessToken } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
    // 1. Fetch recent messages with legal keywords
    const query = encodeURIComponent('subject:(intimação OR "diário de justiça" OR "pje" OR processo OR prazo OR tribunal) OR "intimação jurídica"');
    const listUrl = `https://gmail.googleapis.com/v1/users/me/messages?q=${query}&maxResults=10`;
    
    const listResponse = await fetch(listUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      }
    });

    if (!listResponse.ok) {
      const errorText = await listResponse.text();
      return res.status(listResponse.status).json({ error: `Erro ao listar mensagens do Gmail: ${errorText}` });
    }

    const listData = await listResponse.json() as { messages?: Array<{ id: string, threadId: string }> };
    
    if (!listData.messages || listData.messages.length === 0) {
      return res.json({ publications: [], count: 0 });
    }

    const fetchedPublications: any[] = [];

    // 2. Fetch details for the first 5 messages
    const messagesToFetch = listData.messages.slice(0, 5);

    for (const msg of messagesToFetch) {
      const detailUrl = `https://gmail.googleapis.com/v1/users/me/messages/${msg.id}?format=full`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (!detailRes.ok) continue;

      const detailData = await detailRes.json() as any;
      const headers = detailData.payload?.headers || [];
      const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
      const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "Desconhecido";
      const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
      const emailDate = dateHeader ? new Date(dateHeader) : new Date();

      // Extract raw snippet or body text
      let bodyText = detailData.snippet || "";
      
      // Look for plain text parts in payload
      const parts = detailData.payload?.parts || [];
      if (parts.length > 0) {
        const textPart = parts.find((p: any) => p.mimeType === "text/plain");
        if (textPart && textPart.body?.data) {
          bodyText = Buffer.from(textPart.body.data, 'base64').toString('utf-8');
        }
      } else if (detailData.payload?.body?.data) {
        bodyText = Buffer.from(detailData.payload.body.data, 'base64').toString('utf-8');
      }

      // Truncate text for prompt token limit safety
      const textToAnalyze = `${subject}\n\nDe: ${from}\n\n${bodyText}`.slice(0, 2500);

      // 3. Process each email with Gemini to check if it represents a judicial notification or subpoena, and extract fields
      const prompt = `Analise o e-mail abaixo. Determine se ele se trata de uma notificação judicial, intimação, publicação de diário oficial ou alerta de processo (PJE). 
      Se for, extraia os dados e preencha a estrutura JSON abaixo. Se NÃO for relacionado a processo judicial ou intimação de advogado, retorne um objeto vazio {}.

      Siga estritamente esta estrutura JSON:
      {
        "processNumber": "Número do processo no formato CNJ (0000000-00.0000.0.00.0000). Se não encontrado, deixe em branco",
        "title": "Um resumo amigável em português (ex: intimação de audiência, réplica, prazo de recurso)",
        "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
        "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
        "deadlineDays": "Número de dias do prazo útil (ex: 5, 15). Se não houver prazo claro, retorne 0",
        "actionRequired": "Recomendação objetiva em português para o advogado"
      }

      Conteúdo do E-mail:
      "${textToAnalyze}"`;

      try {
        const aiResponse = await ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json",
          }
        });

        const textResponse = aiResponse.text;
        if (textResponse) {
          const parsed = JSON.parse(textResponse.trim());
          // If the parsed object is not empty, include it in the results
          if (parsed && (parsed.processNumber || parsed.title)) {
            const deadlineDays = parseInt(parsed.deadlineDays) || 0;
            const dueDate = deadlineDays > 0 
              ? calculateBusinessDaysDate(emailDate, deadlineDays)
              : emailDate.toISOString();

            fetchedPublications.push({
              id: `gmail-${msg.id}`,
              processNumber: parsed.processNumber || "Não identificado",
              title: parsed.title || `E-mail: ${subject}`,
              content: `De: ${from}\nAssunto: ${subject}\n\n${bodyText.slice(0, 800)}...`,
              source: "gmail",
              category: parsed.category || "informativo",
              urgencyLevel: parsed.urgencyLevel || "baixa",
              subpoenaDate: emailDate.toISOString(),
              deadlineDays: deadlineDays,
              dueDate: dueDate,
              actionRequired: parsed.actionRequired || "Verificar teor do e-mail recebido.",
              status: "pendente",
              createdAt: new Date().toISOString()
            });
          }
        }
      } catch (innerErr) {
        console.error(`Erro ao analisar mensagem ${msg.id} com Gemini:`, innerErr);
      }
    }

    return res.json({ publications: fetchedPublications, count: fetchedPublications.length });

  } catch (error: any) {
    console.error("Erro ao sincronizar Gmail:", error);
    return res.status(500).json({ error: "Falha na sincronização do Gmail: " + error.message });
  }
});

// Helper function to fetch Gmail PUSH stats with full pagination support
async function fetchGmailPushStats(accessToken: string, sender: string) {
  try {
    // 1. Get total emails in inbox
    let totalCount = 0;
    let nextPageToken: string | undefined = undefined;
    let newestMessageId: string | null = null;

    const baseQuery = `in:inbox from:(${sender})`;
    
    do {
      const url: string = `https://gmail.googleapis.com/v1/users/me/messages?q=${encodeURIComponent(baseQuery)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        throw new Error(`Erro na listagem da API do Gmail: ${errText}`);
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        if (!newestMessageId) {
          newestMessageId = data.messages[0].id;
        }
        totalCount += data.messages.length;
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    // 2. Get unread emails in inbox
    let unreadCount = 0;
    let nextUnreadPageToken: string | undefined = undefined;
    const unreadQuery = `in:inbox is:unread from:(${sender})`;

    do {
      const url: string = `https://gmail.googleapis.com/v1/users/me/messages?q=${encodeURIComponent(unreadQuery)}&maxResults=500${nextUnreadPageToken ? `&pageToken=${nextUnreadPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        throw new Error(`Erro na listagem de mensagens não lidas no Gmail: ${errText}`);
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages) {
        unreadCount += data.messages.length;
      }
      nextUnreadPageToken = data.nextPageToken;
    } while (nextUnreadPageToken);

    // 3. Get details of the newest message if exists
    let newestSubject = "Nenhum e-mail recente";
    let newestDate: string | null = null;

    if (newestMessageId) {
      const detailUrl = `https://gmail.googleapis.com/v1/users/me/messages/${newestMessageId}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (detailRes.ok) {
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        newestSubject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        newestDate = dateHeader ? new Date(dateHeader).toISOString() : null;
      }
    }

    return {
      sender,
      totalCount,
      unreadCount,
      newestSubject,
      newestDate,
      success: true
    };

  } catch (error: any) {
    console.error(`Erro ao buscar estatísticas do PUSH para ${sender}:`, error);
    return {
      sender,
      totalCount: 0,
      unreadCount: 0,
      newestSubject: "Erro de conexão ou token inválido",
      newestDate: null,
      success: false,
      error: error.message
    };
  }
}

// 2.5 API: Gmail Pushes statistics (queries counts and latest push info for courtroom systems)
app.post("/api/gmail-pushes", async (req, res) => {
  const { accessToken, sender } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  const PUSH_SOURCES = [
    { id: "trt-mg", name: "Push TRT-MG", sender: "nao-responda@trt3.jus.br" },
    { id: "pje-mg", name: "Push – PJe MG", sender: "pje@tjmg.jus.br" },
    { id: "tjmg", name: "Push TJMG", sender: "push@tjmg.jus.br" },
    { id: "eproc-tjmg", name: "Push Eproc TJMG", sender: "noreply@tjmg.jus.br" },
    { id: "trf6", name: "Eproc – Push TRF6", sender: "eproc@trf6.jus.br" }
  ];

  try {
    if (sender) {
      const stats = await fetchGmailPushStats(accessToken, sender);
      return res.json({ stats: [stats] });
    } else {
      const promises = PUSH_SOURCES.map(source => fetchGmailPushStats(accessToken, source.sender));
      const results = await Promise.all(promises);
      return res.json({ stats: results });
    }
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-pushes:", error);
    return res.status(500).json({ error: "Falha ao recuperar estatísticas dos PUSHes: " + error.message });
  }
});

// 3. LEGACY INTEGRATION API Endpoints
// Expose endpoint for legacy CRM/ERP to POST publications
app.post("/api/legacy/publications", async (req, res) => {
  const { token, processNumber, title, content, subpoenaDate } = req.body as LegacyPublicationInput;

  if (!token) {
    return res.status(401).json({ error: "Token de autorização da API legada é obrigatório." });
  }

  if (!validTokens.includes(token)) {
    return res.status(403).json({ error: "Token inválido ou expirado." });
  }

  if (!processNumber || !content) {
    return res.status(400).json({ error: "ProcessNumber e Content são campos obrigatórios." });
  }

  try {
    // Run AI analysis on the raw legacy text
    const prompt = `Analise o texto recebido de um sistema jurídico legado e retorne uma classificação JSON.
    Siga estritamente esta estrutura JSON:
    {
      "title": "Um resumo amigável do assunto em português",
      "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
      "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
      "deadlineDays": "Prazo em dias (inteiro). Se não identificado, use 0",
      "actionRequired": "Recomendação de providência para o advogado"
    }

    Texto:
    "${content}"`;

    const aiRes = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const aiText = aiRes.text;
    const parsed = aiText ? JSON.parse(aiText.trim()) : {};

    const rawDate = subpoenaDate ? new Date(subpoenaDate) : new Date();
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(rawDate, deadlineDays)
      : rawDate.toISOString();

    const newLegacyPub = {
      id: `legacy-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      processNumber: processNumber,
      title: title || parsed.title || "Intimação Recebida via API",
      content: content,
      source: "legacy_api",
      category: parsed.category || "prazo",
      urgencyLevel: parsed.urgencyLevel || "media",
      subpoenaDate: rawDate.toISOString(),
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar publicação integrada via API.",
      status: "pendente",
      createdAt: new Date().toISOString()
    };

    legacyPublicationsPool.unshift(newLegacyPub);

    return res.json({
      success: true,
      message: "Publicação recebida e analisada com IA com sucesso.",
      publication: newLegacyPub
    });

  } catch (error: any) {
    console.error("Erro no processamento da API legada:", error);
    return res.status(500).json({ error: "Falha ao processar postagem da API legada: " + error.message });
  }
});

// Endpoint to list all publications received from legacy API
app.get("/api/legacy/publications", (req, res) => {
  return res.json({ publications: legacyPublicationsPool });
});

// Endpoint to generate/register a new API Token
app.post("/api/legacy/tokens", (req, res) => {
  const { name } = req.body;
  if (!name) {
    return res.status(400).json({ error: "Nome do sistema integrado é obrigatório." });
  }
  const newToken = `BOSS_API_TOKEN_${Math.random().toString(36).substring(2, 15).toUpperCase()}`;
  validTokens.push(newToken);
  return res.json({ token: newToken, name: name, createdAt: new Date().toISOString() });
});

// Serve static build in production or mount Vite middleware in development
async function startServer() {
  if (process.env.NODE_ENV === "production") {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  } else {
    // Vite dev mode middleware
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
