import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// In-memory store for Legacy API publications (simulating external CRM/ERP integration)
interface LegacyPublicationInput {
  token: string;
  processNumber: string;
  title: string;
  content: string;
  source?: string;
  subpoenaDate?: string;
}

let legacyPublicationsPool: any[] = [
  {
    id: "leg-1",
    processNumber: "1002345-67.2026.8.26.0100",
    title: "Intimação para réplica - Processo Cível",
    content: "Fica o autor intimado para manifestar-se sobre a contestação apresentada pelo réu no prazo legal de 15 dias úteis.",
    source: "legacy_api",
    category: "prazo",
    urgencyLevel: "media",
    subpoenaDate: new Date().toISOString(),
    deadlineDays: 15,
    dueDate: calculateBusinessDaysDate(new Date(), 15),
    actionRequired: "Elaborar réplica à contestação contestando as preliminares e o mérito alegado pelo réu.",
    status: "pendente",
    createdAt: new Date().toISOString()
  }
];

// In-memory store for API Tokens generated by users
let validTokens: string[] = ["BOSS_LEGACY_INTEGRATION_TOKEN_DEFAULT"];

// Helper to calculate business days (skips Saturday & Sunday)
function calculateBusinessDaysDate(startDate: Date, days: number): string {
  let resultDate = new Date(startDate);
  let count = 0;
  while (count < days) {
    resultDate.setDate(resultDate.getDate() + 1);
    const dayOfWeek = resultDate.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) { // 0 = Sunday, 6 = Saturday
      count++;
    }
  }
  return resultDate.toISOString();
}

// Helper to execute promises with a concurrency limit
async function fetchWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  const executing: Promise<any>[] = [];
  for (const item of items) {
    const p = Promise.resolve().then(() => fn(item));
    results.push(p as any);
    if (limit <= items.length) {
      const e: any = p.then(() => executing.splice(executing.indexOf(e), 1));
      executing.push(e);
      if (executing.length >= limit) {
        await Promise.race(executing);
      }
    }
  }
  return Promise.all(results);
}

// Helper to extract CNJ process numbers from text with whitespace tolerance
function extractCNJsFromText(text: string): string[] {
  if (!text) return [];
  const regex = /\d{7}\s*-\s*\d{2}\s*\.\s*\d{4}\s*\.\s*\d\s*\.\s*\d{2}\s*\.\s*\d{4}/g;
  const matches = text.match(regex);
  if (!matches) return [];
  const unique = new Set<string>();
  for (const m of matches) {
    const cleaned = m.replace(/\s+/g, '');
    unique.add(cleaned);
  }
  return Array.from(unique);
}

// 1. API: AI Analyzer for manual copy-pasted publications
app.post("/api/analyze-publication", async (req, res) => {
  const { content, subpoenaDate } = req.body;

  if (!content) {
    return res.status(400).json({ error: "O conteúdo da publicação é obrigatório." });
  }

  const dateToUse = subpoenaDate ? new Date(subpoenaDate) : new Date();

  try {
    const prompt = `Analise o texto de intimação/publicação jurídica abaixo e retorne um objeto JSON contendo as informações extraídas.
    Siga estritamente esta estrutura JSON:
    {
      "processNumber": "Número do processo no padrão CNJ (ex: 0000000-00.0000.0.00.0000). Se não encontrar, tente identificar um formato similar ou deixe vazio",
      "title": "Um título curto e claro em português explicando o assunto (ex: 'Apresentar réplica à contestação')",
      "category": "Escolha uma destas opções exatas: 'urgente' (prazos fatais de 1 a 3 dias ou liminares), 'prazo' (outros prazos normais), 'informativo' (sem prazo, apenas ciência), 'audiencia' (marcação de audiência/julgamento)",
      "urgencyLevel": "Escolha uma destas opções exatas: 'alta' (prazos curtos ou liminares), 'media' (prazos normais de 15 dias), 'baixa' (ciência ou prazos longos)",
      "deadlineDays": "Número inteiro representando o prazo em dias (ex: 15). Se não houver prazo claro, retorne 0",
      "actionRequired": "Instruções claras e objetivas em português para o advogado tomar as providências adequadas"
    }

    Texto da publicação:
    "${content}"`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("Sem resposta do modelo Gemini.");
    }

    const parsed = JSON.parse(responseText.trim());
    
    // Calculate due date based on calculated business days
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(dateToUse, deadlineDays)
      : dateToUse.toISOString();

    return res.json({
      processNumber: parsed.processNumber || "Não identificado",
      title: parsed.title || "Publicação Jurídica",
      category: parsed.category || "informativo",
      urgencyLevel: parsed.urgencyLevel || "baixa",
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar teor da publicação.",
      content: content,
      subpoenaDate: dateToUse.toISOString()
    });

  } catch (error: any) {
    console.error("Erro na análise do Gemini:", error);
    return res.status(500).json({ error: "Erro ao processar análise da publicação com IA: " + error.message });
  }
});

// 2. API: Gmail Sync (queries Gmail using OAuth Access Token passed by frontend)
app.post("/api/gmail-sync", async (req, res) => {
  const { accessToken } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
        // 1. Fetch recent messages with legal keywords
    const query = encodeURIComponent('subject:(intimação OR "diário de justiça" OR "pje" OR processo OR prazo OR tribunal) OR "intimação jurídica"');
    const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${query}&maxResults=10`;
    
    const listResponse = await fetch(listUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      }
    });

    if (!listResponse.ok) {
      const errorText = await listResponse.text();
      return res.status(listResponse.status).json({ error: `Erro ao listar mensagens do Gmail: ${errorText}` });
    }

    const listData = await listResponse.json() as { messages?: Array<{ id: string, threadId: string }> };
    
    if (!listData.messages || listData.messages.length === 0) {
      return res.json({ publications: [], count: 0 });
    }

    const fetchedPublications: any[] = [];

    // 2. Fetch details for the first 5 messages
    const messagesToFetch = listData.messages.slice(0, 5);

    for (const msg of messagesToFetch) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (!detailRes.ok) continue;

      const detailData = await detailRes.json() as any;
      const headers = detailData.payload?.headers || [];
      const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
      const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "Desconhecido";
      const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
      const emailDate = dateHeader ? new Date(dateHeader) : new Date();

      // Extract raw snippet or body text
      let bodyText = detailData.snippet || "";
      
      // Look for plain text parts in payload
      const parts = detailData.payload?.parts || [];
      if (parts.length > 0) {
        const textPart = parts.find((p: any) => p.mimeType === "text/plain");
        if (textPart && textPart.body?.data) {
          bodyText = Buffer.from(textPart.body.data, 'base64').toString('utf-8');
        }
      } else if (detailData.payload?.body?.data) {
        bodyText = Buffer.from(detailData.payload.body.data, 'base64').toString('utf-8');
      }

      // Truncate text for prompt token limit safety
      const textToAnalyze = `${subject}\n\nDe: ${from}\n\n${bodyText}`.slice(0, 2500);

      // 3. Process each email with Gemini to check if it represents a judicial notification or subpoena, and extract fields
      const prompt = `Analise o e-mail abaixo. Determine se ele se trata de uma notificação judicial, intimação, publicação de diário oficial ou alerta de processo (PJE). 
      Se for, extraia os dados e preencha a estrutura JSON abaixo. Se NÃO for relacionado a processo judicial ou intimação de advogado, retorne um objeto vazio {}.

      Siga estritamente esta estrutura JSON:
      {
        "processNumber": "Número do processo no formato CNJ (0000000-00.0000.0.00.0000). Se não encontrado, deixe em branco",
        "title": "Um resumo amigável em português (ex: intimação de audiência, réplica, prazo de recurso)",
        "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
        "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
        "deadlineDays": "Número de dias do prazo útil (ex: 5, 15). Se não houver prazo claro, retorne 0",
        "actionRequired": "Recomendação objetiva em português para o advogado"
      }

      Conteúdo do E-mail:
      "${textToAnalyze}"`;

      try {
        const aiResponse = await ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json",
          }
        });

        const textResponse = aiResponse.text;
        if (textResponse) {
          const parsed = JSON.parse(textResponse.trim());
          // If the parsed object is not empty, include it in the results
          if (parsed && (parsed.processNumber || parsed.title)) {
            const deadlineDays = parseInt(parsed.deadlineDays) || 0;
            const dueDate = deadlineDays > 0 
              ? calculateBusinessDaysDate(emailDate, deadlineDays)
              : emailDate.toISOString();

            fetchedPublications.push({
              id: `gmail-${msg.id}`,
              processNumber: parsed.processNumber || "Não identificado",
              title: parsed.title || `E-mail: ${subject}`,
              content: `De: ${from}\nAssunto: ${subject}\n\n${bodyText.slice(0, 800)}...`,
              source: "gmail",
              category: parsed.category || "informativo",
              urgencyLevel: parsed.urgencyLevel || "baixa",
              subpoenaDate: emailDate.toISOString(),
              deadlineDays: deadlineDays,
              dueDate: dueDate,
              actionRequired: parsed.actionRequired || "Verificar teor do e-mail recebido.",
              status: "pendente",
              createdAt: new Date().toISOString()
            });
          }
        }
      } catch (innerErr) {
        console.error(`Erro ao analisar mensagem ${msg.id} com Gemini:`, innerErr);
      }
    }

    return res.json({ publications: fetchedPublications, count: fetchedPublications.length });

  } catch (error: any) {
    console.error("Erro ao sincronizar Gmail:", error);
    return res.status(500).json({ error: "Falha na sincronização do Gmail: " + error.message });
  }
});

// Helper function to fetch Gmail PUSH stats with full pagination support
async function fetchGmailPushStats(accessToken: string, sender: string) {
  try {
    // 1. Get total emails in inbox
    let totalCount = 0;
    let nextPageToken: string | undefined = undefined;
    let newestMessageId: string | null = null;

    const baseQuery = `in:inbox from:(${sender})`;
    
    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(baseQuery)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Remetente consultado: ${sender}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        if (!newestMessageId) {
          newestMessageId = data.messages[0].id;
        }
        totalCount += data.messages.length;
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    // 2. Get unread emails in inbox
    let unreadCount = 0;
    let nextUnreadPageToken: string | undefined = undefined;
    const unreadQuery = `in:inbox is:unread from:(${sender})`;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(unreadQuery)}&maxResults=500${nextUnreadPageToken ? `&pageToken=${nextUnreadPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Remetente consultado: ${sender}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages) {
        unreadCount += data.messages.length;
      }
      nextUnreadPageToken = data.nextPageToken;
    } while (nextUnreadPageToken);

    // 3. Get details of the newest message if exists
    let newestSubject = "Nenhum e-mail recente";
    let newestDate: string | null = null;

    if (newestMessageId) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMessageId}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (detailRes.ok) {
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        newestSubject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        newestDate = dateHeader ? new Date(dateHeader).toISOString() : null;
      }
    }

    return {
      sender,
      totalCount,
      unreadCount,
      newestSubject,
      newestDate,
      success: true
    };

  } catch (error: any) {
    console.error(`Erro ao buscar estatísticas do PUSH para ${sender}:`, error);
    return {
      sender,
      totalCount: 0,
      unreadCount: 0,
      newestSubject: "Erro de consulta",
      newestDate: null,
      success: false,
      error: error.message || "Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente."
    };
  }
}

// 2.5 API: Gmail Pushes statistics (queries counts and latest push info for courtroom systems)
app.post("/api/gmail-pushes", async (req, res) => {
  const { accessToken, sender } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  const PUSH_SOURCES = [
    { id: "trt-mg", name: "Push TRT-MG", sender: "nao-responda@trt3.jus.br" },
    { id: "pje-mg", name: "Push – PJe MG", sender: "pje@tjmg.jus.br" },
    { id: "tjmg", name: "Push TJMG", sender: "push@tjmg.jus.br" },
    { id: "eproc-tjmg", name: "Push Eproc TJMG", sender: "noreply@tjmg.jus.br" },
    { id: "trf6", name: "Eproc – Push TRF6", sender: "eproc@trf6.jus.br" }
  ];

  try {
    if (sender) {
      const stats = await fetchGmailPushStats(accessToken, sender);
      return res.json({ stats: [stats] });
    } else {
      const promises = PUSH_SOURCES.map(source => fetchGmailPushStats(accessToken, source.sender));
      const results = await Promise.all(promises);
      return res.json({ stats: results });
    }
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-pushes:", error);
    return res.status(500).json({ error: "Falha ao recuperar estatísticas dos PUSHes: " + error.message });
  }
});

// 2.6 API: Gmail Pushes grouped by CNJ (for the operational cleaning and checking panel)
app.post("/api/gmail-pushes/grouped-by-cnj", async (req, res) => {
  const { accessToken, sender, page = 1, limit = 50, search = "" } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!sender) {
    return res.status(400).json({ error: "Remetente do push (sender) não fornecido." });
  }

  try {
    let messages: Array<{ id: string, threadId: string }> = [];
    let nextPageToken: string | undefined = undefined;
    let q = `in:inbox from:(${sender})`;
    if (search && search.trim() !== "") {
      q += ` "${search.trim()}"`;
    }

    let pageCount = 0;
    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(q)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const apiRes = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      if (!apiRes.ok) {
        const errText = await apiRes.text();
        throw new Error(`Erro ao listar mensagens do Gmail: ${errText}`);
      }
      const data = await apiRes.json() as any;
      if (data.messages) {
        messages = messages.concat(data.messages);
      }
      nextPageToken = data.nextPageToken;
      pageCount++;
    } while (nextPageToken && pageCount < 3); // limit to 1500 messages max to prevent timeout

    const totalEmails = messages.length;

    // Fetch details for all messages with concurrency control (up to 40 parallel requests)
    const msgDetails = await fetchWithConcurrency(messages, 40, async (msg) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        if (!detailRes.ok) return null;
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();
        const snippet = detailData.snippet || "";
        const labelIds = detailData.labelIds || [];
        const isUnread = labelIds.includes("UNREAD");

        return {
          id: msg.id,
          threadId: msg.threadId,
          subject,
          snippet,
          date: emailDate,
          isUnread
        };
      } catch (err) {
        console.error(`Erro ao buscar detalhes da mensagem ${msg.id}:`, err);
        return null;
      }
    });

    const validDetails = msgDetails.filter((m): m is any => m !== null);

    // Filter out messages that don't have CNJs in subject or snippet, to fetch bodyText and try finding CNJ there
    const messagesWithoutCnj = validDetails.filter(m => {
      const subjectCnjs = extractCNJsFromText(m.subject);
      const snippetCnjs = extractCNJsFromText(m.snippet);
      return subjectCnjs.length === 0 && snippetCnjs.length === 0;
    });

    // Fetch full format only for up to 30 messages without CNJ to avoid rate limiting
    const bodyFetchedMsgs = await fetchWithConcurrency(messagesWithoutCnj.slice(0, 30), 15, async (msg) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        if (!detailRes.ok) return null;
        const detailData = await detailRes.json() as any;
        
        let bodyText = detailData.snippet || "";
        const parts = detailData.payload?.parts || [];
        if (parts.length > 0) {
          const textPart = parts.find((p: any) => p.mimeType === "text/plain");
          if (textPart && textPart.body?.data) {
            bodyText = Buffer.from(textPart.body.data, 'base64').toString('utf-8');
          }
        } else if (detailData.payload?.body?.data) {
          bodyText = Buffer.from(detailData.payload.body.data, 'base64').toString('utf-8');
        }
        
        return {
          id: msg.id,
          bodyText
        };
      } catch (err) {
        return null;
      }
    });

    const bodyTextMap = new Map<string, string>();
    for (const b of bodyFetchedMsgs) {
      if (b) bodyTextMap.set(b.id, b.bodyText);
    }

    // Now process and extract all CNJs
    const processedMessages = validDetails.map(msg => {
      let cnjs = Array.from(new Set([
        ...extractCNJsFromText(msg.subject),
        ...extractCNJsFromText(msg.snippet)
      ]));

      if (cnjs.length === 0) {
        const bodyText = bodyTextMap.get(msg.id);
        if (bodyText) {
          cnjs = extractCNJsFromText(bodyText);
        }
      }

      return {
        ...msg,
        cnjs
      };
    });

    // Grouping by CNJ
    // Key: CNJ number, or "Não identificado"
    const cnjGroupsMap = new Map<string, any>();
    const unassignedGroup: any[] = [];

    // Helper to get Source ID from sender email
    const PUSH_SOURCES_MAP = [
      { id: "trt-mg", sender: "nao-responda@trt3.jus.br" },
      { id: "pje-mg", sender: "pje@tjmg.jus.br" },
      { id: "tjmg", sender: "push@tjmg.jus.br" },
      { id: "eproc-tjmg", sender: "noreply@tjmg.jus.br" },
      { id: "trf6", sender: "eproc@trf6.jus.br" }
    ];
    const sourceId = PUSH_SOURCES_MAP.find(s => s.sender === sender)?.id || "trt-mg";

    for (const msg of processedMessages) {
      if (msg.cnjs.length === 0) {
        unassignedGroup.push(msg);
      } else {
        for (const cnj of msg.cnjs) {
          if (!cnjGroupsMap.has(cnj)) {
            cnjGroupsMap.set(cnj, {
              processNumber: cnj,
              messages: [],
              totalCount: 0,
              unreadCount: 0,
              latestSubject: "",
              latestDate: ""
            });
          }
          const group = cnjGroupsMap.get(cnj);
          group.messages.push(msg);
        }
      }
    }

    // Finalize groups
    const groupsList: any[] = [];
    for (const [cnj, group] of cnjGroupsMap.entries()) {
      // Sort messages in group by date descending to get the latest subject/date
      group.messages.sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime());
      
      const unreadCount = group.messages.filter((m: any) => m.isUnread).length;
      const latestMessage = group.messages[0];

      // Build URLs
      const gmailSearchUrl = `https://mail.google.com/mail/u/0/#search/in%3Ainbox+from%3A${encodeURIComponent(sender)}+%22${encodeURIComponent(cnj)}%22`;
      const todoistUrl = `https://app.todoist.com/app/search/${encodeURIComponent(cnj)}?intent=searchCompleted`;
      
      let courtSearchUrl = `https://pje.trt3.jus.br/consultaprocessual/detalhe-processo/${cnj}`;
      if (sourceId === "pje-mg" || sourceId === "tjmg") {
        courtSearchUrl = "https://pje.tjmg.jus.br/pje/ConsultaPublica/listView.seam";
      } else if (sourceId === "eproc-tjmg") {
        courtSearchUrl = "https://eproc.tjmg.jus.br/eproc/externo_controlador.php?controle=publicacao_pesquisa";
      } else if (sourceId === "trf6") {
        courtSearchUrl = "https://eproc.trf6.jus.br/eproc/externo_controlador.php?controle=publicacao_pesquisa";
      }

      groupsList.push({
        processNumber: cnj,
        totalCount: group.messages.length,
        unreadCount,
        latestSubject: latestMessage.subject,
        latestDate: latestMessage.date,
        messageIds: group.messages.map((m: any) => m.id),
        gmailSearchUrl,
        todoistUrl,
        courtSearchUrl,
        messages: group.messages
      });
    }

    // Sort valid CNJ groups from highest email count to lowest
    groupsList.sort((a, b) => b.totalCount - a.totalCount);

    // If there are unassigned messages, append a "Não identificado" group at the end
    if (unassignedGroup.length > 0) {
      unassignedGroup.sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime());
      const unreadCount = unassignedGroup.filter((m: any) => m.isUnread).length;
      const latestMessage = unassignedGroup[0];

      groupsList.push({
        processNumber: "Não identificado",
        totalCount: unassignedGroup.length,
        unreadCount,
        latestSubject: latestMessage.subject,
        latestDate: latestMessage.date,
        messageIds: unassignedGroup.map((m: any) => m.id),
        gmailSearchUrl: `https://mail.google.com/mail/u/0/#search/in%3Ainbox+from%3A${encodeURIComponent(sender)}`,
        todoistUrl: "",
        courtSearchUrl: "",
        messages: unassignedGroup
      });
    }

    const totalProcesses = cnjGroupsMap.size;

    // Apply pagination
    const pageNum = parseInt(page as any || "1", 10);
    const limitNum = parseInt(limit as any || "50", 10);
    const startIndex = (pageNum - 1) * limitNum;
    const endIndex = pageNum * limitNum;
    const paginatedGroups = groupsList.slice(startIndex, endIndex);

    return res.json({
      sender,
      totalEmails,
      totalProcesses,
      page: pageNum,
      limit: limitNum,
      totalPages: Math.ceil(groupsList.length / limitNum),
      groups: paginatedGroups
    });

  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-pushes/grouped-by-cnj:", error);
    return res.status(500).json({ error: "Falha ao agrupar PUSHes por CNJ: " + error.message });
  }
});

// 2.7 API: Mark Gmail messages as read in batch
app.post("/api/gmail-pushes/mark-as-read", async (req, res) => {
  const { accessToken, messageIds } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Lista de messageIds é obrigatória." });
  }

  try {
    const url = "https://gmail.googleapis.com/gmail/v1/users/me/messages/batchModify";
    const apiRes = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        ids: messageIds,
        removeLabelIds: ["UNREAD"]
      })
    });

    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Erro ao marcar mensagens como lidas: ${errText}`);
    }

    return res.json({ success: true, count: messageIds.length });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-pushes/mark-as-read:", error);
    return res.status(500).json({ error: "Falha ao marcar PUSHes como lidos: " + error.message });
  }
});

// 3. LEGACY INTEGRATION API Endpoints
// Expose endpoint for legacy CRM/ERP to POST publications
app.post("/api/legacy/publications", async (req, res) => {
  const { token, processNumber, title, content, subpoenaDate } = req.body as LegacyPublicationInput;

  if (!token) {
    return res.status(401).json({ error: "Token de autorização da API legada é obrigatório." });
  }

  if (!validTokens.includes(token)) {
    return res.status(403).json({ error: "Token inválido ou expirado." });
  }

  if (!processNumber || !content) {
    return res.status(400).json({ error: "ProcessNumber e Content são campos obrigatórios." });
  }

  try {
    // Run AI analysis on the raw legacy text
    const prompt = `Analise o texto recebido de um sistema jurídico legado e retorne uma classificação JSON.
    Siga estritamente esta estrutura JSON:
    {
      "title": "Um resumo amigável do assunto em português",
      "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
      "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
      "deadlineDays": "Prazo em dias (inteiro). Se não identificado, use 0",
      "actionRequired": "Recomendação de providência para o advogado"
    }

    Texto:
    "${content}"`;

    const aiRes = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const aiText = aiRes.text;
    const parsed = aiText ? JSON.parse(aiText.trim()) : {};

    const rawDate = subpoenaDate ? new Date(subpoenaDate) : new Date();
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(rawDate, deadlineDays)
      : rawDate.toISOString();

    const newLegacyPub = {
      id: `legacy-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      processNumber: processNumber,
      title: title || parsed.title || "Intimação Recebida via API",
      content: content,
      source: "legacy_api",
      category: parsed.category || "prazo",
      urgencyLevel: parsed.urgencyLevel || "media",
      subpoenaDate: rawDate.toISOString(),
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar publicação integrada via API.",
      status: "pendente",
      createdAt: new Date().toISOString()
    };

    legacyPublicationsPool.unshift(newLegacyPub);

    return res.json({
      success: true,
      message: "Publicação recebida e analisada com IA com sucesso.",
      publication: newLegacyPub
    });

  } catch (error: any) {
    console.error("Erro no processamento da API legada:", error);
    return res.status(500).json({ error: "Falha ao processar postagem da API legada: " + error.message });
  }
});

// Endpoint to list all publications received from legacy API
app.get("/api/legacy/publications", (req, res) => {
  return res.json({ publications: legacyPublicationsPool });
});

// Endpoint to generate/register a new API Token
app.post("/api/legacy/tokens", (req, res) => {
  const { name } = req.body;
  if (!name) {
    return res.status(400).json({ error: "Nome do sistema integrado é obrigatório." });
  }
  const newToken = `BOSS_API_TOKEN_${Math.random().toString(36).substring(2, 15).toUpperCase()}`;
  validTokens.push(newToken);
  return res.json({ token: newToken, name: name, createdAt: new Date().toISOString() });
});

// Helper function to fetch Gmail stats for a custom search query with full pagination
async function fetchGmailStatsForQuery(accessToken: string, queryStr: string) {
  try {
    let totalCount = 0;
    let nextPageToken: string | undefined = undefined;
    let newestMessageId: string | null = null;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(queryStr)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Consulta realizada: ${queryStr}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        if (!newestMessageId) {
          newestMessageId = data.messages[0].id;
        }
        totalCount += data.messages.length;
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    let unreadQuery = queryStr;
    if (!queryStr.includes("is:unread") && !queryStr.includes("is:read")) {
      unreadQuery = `(${queryStr}) is:unread`;
    }

    let unreadCount = 0;
    let nextUnreadPageToken: string | undefined = undefined;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(unreadQuery)}&maxResults=500${nextUnreadPageToken ? `&pageToken=${nextUnreadPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        const errText = await res.text();
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Consulta realizada: ${unreadQuery}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages) {
        unreadCount += data.messages.length;
      }
      nextUnreadPageToken = data.nextPageToken;
    } while (nextUnreadPageToken);

    let newestSubject = "Nenhum e-mail recente";
    let newestDate: string | null = null;

    if (newestMessageId) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMessageId}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (detailRes.ok) {
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        newestSubject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        newestDate = dateHeader ? new Date(dateHeader).toISOString() : null;
      }
    }

    return {
      query: queryStr,
      totalCount,
      unreadCount,
      newestSubject,
      newestDate,
      success: true
    };
  } catch (error: any) {
    console.error(`Erro ao buscar estatísticas do Gmail para query (${queryStr}):`, error);
    return {
      query: queryStr,
      totalCount: 0,
      unreadCount: 0,
      newestSubject: "Erro de consulta",
      newestDate: null,
      success: false,
      error: error.message || "Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente."
    };
  }
}

// Prius Integration Real-check Endpoint
app.post("/api/prius/sync", async (req, res) => {
  const { accessToken } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }

  try {
    const queryStr = `in:inbox (from:(prius) OR subject:(prius) OR "PRIUS")`;
    const stats = await fetchGmailStatsForQuery(accessToken, queryStr);
    
    return res.json({ 
      success: stats.success, 
      count: stats.totalCount, 
      unreadCount: stats.unreadCount,
      newestSubject: stats.newestSubject,
      newestDate: stats.newestDate,
      error: stats.error || null,
      publications: [] 
    });
  } catch (error: any) {
    console.error("Erro no sync Prius:", error);
    return res.status(500).json({ error: "Falha na varredura do Prius via Gmail: " + error.message });
  }
});

// Recorte Digital Integration Real-check Endpoint
app.post("/api/recorte-digital/sync", async (req, res) => {
  const { accessToken, serviceId } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }

  if (!serviceId) {
    return res.status(400).json({ error: "Service ID não fornecido." });
  }

  try {
    // Map serviceId to its respective Gmail query
    let queryStr = "";
    if (serviceId === 'oab-mg') {
      queryStr = `in:inbox ("Recorte Digital" "OAB/MG")`;
    } else if (serviceId === 'rj') {
      queryStr = `in:inbox ("Recorte Digital" "RJ")`;
    } else if (serviceId === 'ceara') {
      queryStr = `in:inbox ("Recorte Digital" "Ceará")`;
    } else if (serviceId === 'sao-paulo') {
      queryStr = `in:inbox ("Recorte Digital" "São Paulo")`;
    } else {
      queryStr = `in:inbox ("Recorte Digital" "${serviceId}")`;
    }

    const stats = await fetchGmailStatsForQuery(accessToken, queryStr);
    
    return res.json({ 
      success: stats.success, 
      count: stats.totalCount, 
      unreadCount: stats.unreadCount,
      newestSubject: stats.newestSubject,
      newestDate: stats.newestDate,
      error: stats.error || null,
      publications: [] 
    });
  } catch (error: any) {
    console.error(`Erro no sync Recorte Digital (${serviceId}):`, error);
    return res.status(500).json({ error: "Falha na varredura do Recorte Digital via Gmail: " + error.message });
  }
});

// Helper to decode Gmail base64
function decodeBase64(data: string): string {
  const normalized = data.replace(/-/g, '+').replace(/_/g, '/');
  return Buffer.from(normalized, 'base64').toString('utf-8');
}

// Helper to recursively parse message body parts
function parseBodyAndAttachments(payload: any): { bodyText: string; hasAttachments: boolean; attachments: any[] } {
  let bodyText = "";
  let hasAttachments = false;
  const attachments: any[] = [];

  function traverseParts(parts: any[]) {
    for (const part of parts) {
      if (part.filename && part.filename.length > 0) {
        hasAttachments = true;
        attachments.push({
          filename: part.filename,
          mimeType: part.mimeType,
          size: part.body?.size || 0,
          attachmentId: part.body?.attachmentId
        });
      }
      
      if (part.mimeType === "text/plain" && part.body?.data) {
        bodyText += decodeBase64(part.body.data);
      } else if (part.mimeType === "text/html" && part.body?.data && !bodyText) {
        const html = decodeBase64(part.body.data);
        bodyText += html.replace(/<[^>]*>/g, " "); // simple HTML tag strip
      }

      if (part.parts) {
        traverseParts(part.parts);
      }
    }
  }

  if (payload.parts) {
    traverseParts(payload.parts);
  } else if (payload.body?.data) {
    if (payload.mimeType === "text/plain") {
      bodyText = decodeBase64(payload.body.data);
    } else if (payload.mimeType === "text/html") {
      const html = decodeBase64(payload.body.data);
      bodyText = html.replace(/<[^>]*>/g, " ");
    }
  }

  return { bodyText: bodyText.trim(), hasAttachments, attachments };
}

// Extract judicial metadata using smart rules
function extractJudicialInfo(subject: string, bodyText: string, snippet: string) {
  const fullText = `${subject}\n${snippet}\n${bodyText}`;

  // 1. CNJ standard format: 0000000-00.0000.0.00.0000
  const cnjRegex = /(\d{7})[-.\s]?(\d{2})[-.\s]?(\d{4})[-.\s]?(\d)[-.\s]?(\d{2})[-.\s]?(\d{4})/g;
  const cnjMatches = [...fullText.matchAll(cnjRegex)];
  let processNumber = "";
  if (cnjMatches.length > 0) {
    const m = cnjMatches[0];
    processNumber = `${m[1]}-${m[2]}.${m[3]}.${m[4]}.${m[5]}.${m[6]}`;
  }

  // 2. Identify Court / Tribunal
  let tribunal = "";
  if (processNumber) {
    const parts = processNumber.split('.');
    if (parts.length >= 5) {
      const jCode = parts[3]; 
      const trCode = parts[4]; 
      if (jCode === '5' && trCode === '03') {
        tribunal = "TRT-3 (MG)";
      } else if (jCode === '8' && trCode === '13') {
        tribunal = "TJMG";
      } else if (jCode === '1' && trCode === '06') {
        tribunal = "TRF-6";
      } else {
        tribunal = `Tribunal (Código ${jCode}.${trCode})`;
      }
    }
  }

  if (!tribunal) {
    if (/trt\s?3|trt3|tribunal regional do trabalho da 3/i.test(fullText)) {
      tribunal = "TRT-3 (MG)";
    } else if (/tjmg|tribunal de justi\u00e7a de minas gerais/i.test(fullText)) {
      tribunal = "TJMG";
    } else if (/trf\s?6|trf6|tribunal regional federal da 6/i.test(fullText)) {
      tribunal = "TRF-6";
    } else if (/pje/i.test(fullText)) {
      tribunal = "PJe";
    } else if (/eproc/i.test(fullText)) {
      tribunal = "Eproc";
    } else {
      tribunal = "Não identificado";
    }
  }

  // 3. Vara
  let vara = "";
  const varaMatch = fullText.match(/(?:vara|juizado|c\u00e2mara|ju\u00edzo)\s+[^,\n.\r]{1,40}/i);
  if (varaMatch) {
    vara = varaMatch[0].trim();
  } else {
    vara = "Não identificada";
  }

  // 4. Classe processual
  let classe = "";
  const classMatch = fullText.match(/(?:classe|procedimento|tipo|a\u00e7\u00e3o):\s*([^,\n.\r]{2,40})/i);
  if (classMatch) {
    classe = classMatch[1].trim();
  } else {
    classe = "Não identificada";
  }

  // 5. Parts (Author/Defendant)
  let autor = "";
  let reu = "";
  
  const reqMatch = fullText.match(/(?:autor|reclamante|requerente|impetrante|polo ativo|recorrente):\s*([^,\n.\r]{2,50})/i);
  if (reqMatch) {
    autor = reqMatch[1].trim();
  } else {
    autor = "Não identificado";
  }

  const resMatch = fullText.match(/(?:r\u00e9u|reclamado|requerido|impetrado|polo passivo|recorrido):\s*([^,\n.\r]{2,50})/i);
  if (resMatch) {
    reu = resMatch[1].trim();
  } else {
    reu = "Não identificado";
  }

  // 6. Tipo de Movimentação
  let movementType = "";
  const movMatch = fullText.match(/(?:movimenta\u00e7\u00e3o|evento|tipo de ato|assunto):\s*([^,\n.\r]{2,60})/i);
  if (movMatch) {
    movementType = movMatch[1].trim();
  } else if (/audi\u00eancia/i.test(fullText)) {
    movementType = "Audiência Designada/Intimação";
  } else if (/senten\u00e7a|decis\u00e3o/i.test(fullText)) {
    movementType = "Sentença / Decisão Proferida";
  } else if (/despacho/i.test(fullText)) {
    movementType = "Despacho Publicado";
  } else {
    movementType = "Publicação Geral";
  }

  return {
    processNumber: processNumber || "Não identificado",
    tribunal,
    vara,
    classe,
    autor,
    reu,
    movementType
  };
}

// Endpoint to list all messages IDs from Gmail for a sender or a custom query
app.post("/api/gmail-messages-list", async (req, res) => {
  const { accessToken, sender, query: clientQuery, filter } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
    let query = "";
    if (clientQuery) {
      query = clientQuery;
    } else if (sender) {
      query = `in:inbox from:(${sender})`;
    } else {
      return res.status(400).json({ error: "Sender ou Query do Gmail não fornecido." });
    }

    if (filter === 'unread' && !query.includes("is:unread") && !query.includes("is:read")) {
      query = `(${query}) is:unread`;
    }

    const messageIds: string[] = [];
    let nextPageToken: string | undefined = undefined;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(query)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`Erro na listagem da API do Gmail: ${errText}`);
      }

      const data = await response.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        data.messages.forEach(m => {
          if (m.id && !messageIds.includes(m.id)) {
            messageIds.push(m.id);
          }
        });
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    return res.json({ success: true, messageIds, totalCount: messageIds.length });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-messages-list:", error);
    return res.status(500).json({ error: "Falha ao recuperar a lista de mensagens do Gmail: " + error.message });
  }
});

// Endpoint to get details for multiple message IDs in batch
app.post("/api/gmail-messages-details", async (req, res) => {
  const { accessToken, messageIds } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Array messageIds inválido ou vazio." });
  }

  try {
    const detailsPromises = messageIds.map(async (id) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${id}?format=full`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });

        if (!detailRes.ok) {
          return { id, success: false, error: `Erro HTTP ${detailRes.status}` };
        }

        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        
        const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "Desconhecido";
        const to = headers.find((h: any) => h.name.toLowerCase() === "to")?.value || "Desconhecido";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
        const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();
        const snippet = detailData.snippet || "";
        
        const labelIds = detailData.labelIds || [];
        const isUnread = labelIds.includes("UNREAD");

        const { bodyText, hasAttachments, attachments } = parseBodyAndAttachments(detailData.payload || {});
        
        const judicialInfo = extractJudicialInfo(subject, bodyText, snippet);

        return {
          id,
          success: true,
          subject,
          from,
          to,
          date: emailDate,
          snippet,
          isUnread,
          hasAttachments,
          attachments,
          bodyText,
          ...judicialInfo
        };
      } catch (err: any) {
        return { id, success: false, error: err.message };
      }
    });

    const results = await Promise.all(detailsPromises);
    return res.json({ success: true, messages: results });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-messages-details:", error);
    return res.status(500).json({ error: "Falha ao obter os detalhes das mensagens do Gmail: " + error.message });
  }
});

// Serve static build in production or mount Vite middleware in development
async function startServer() {
  if (process.env.NODE_ENV === "production") {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  } else {
    // Vite dev mode middleware
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
