import express from "express";
import path from "path";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";
import { ComunicaApiService } from "./src/services/comunicaApiService.js";

// Load environment variables
dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Gemini Client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// In-memory store for Legacy API publications (simulating external CRM/ERP integration)
interface LegacyPublicationInput {
  token: string;
  processNumber: string;
  title: string;
  content: string;
  source?: string;
  subpoenaDate?: string;
}

let legacyPublicationsPool: any[] = [];

// In-memory store for API Tokens generated by users
let validTokens: string[] = [];

// Helper to calculate business days (skips Saturday & Sunday)
function calculateBusinessDaysDate(startDate: Date, days: number): string {
  let resultDate = new Date(startDate);
  let count = 0;
  while (count < days) {
    resultDate.setDate(resultDate.getDate() + 1);
    const dayOfWeek = resultDate.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) { // 0 = Sunday, 6 = Saturday
      count++;
    }
  }
  return resultDate.toISOString();
}

// Helper to execute promises with a concurrency limit
async function fetchWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>
): Promise<R[]> {
  const results: R[] = [];
  const executing: Promise<any>[] = [];
  for (const item of items) {
    const p = Promise.resolve().then(() => fn(item));
    results.push(p as any);
    if (limit <= items.length) {
      const e: any = p.then(() => executing.splice(executing.indexOf(e), 1));
      executing.push(e);
      if (executing.length >= limit) {
        await Promise.race(executing);
      }
    }
  }
  return Promise.all(results);
}

// Helper to extract CNJ process numbers from text with whitespace tolerance
function extractCNJsFromText(text: string): string[] {
  if (!text) return [];
  const regex = /\d{7}\s*-\s*\d{2}\s*\.\s*\d{4}\s*\.\s*\d\s*\.\s*\d{2}\s*\.\s*\d{4}/g;
  const matches = text.match(regex);
  if (!matches) return [];
  const unique = new Set<string>();
  for (const m of matches) {
    const cleaned = m.replace(/\s+/g, '');
    unique.add(cleaned);
  }
  return Array.from(unique);
}

// 1. API: AI Analyzer for manual copy-pasted publications
app.post("/api/analyze-publication", async (req, res) => {
  const { content, subpoenaDate } = req.body;

  if (!content) {
    return res.status(400).json({ error: "O conteúdo da publicação é obrigatório." });
  }

  const dateToUse = subpoenaDate ? new Date(subpoenaDate) : new Date();

  try {
    const prompt = `Analise o texto de intimação/publicação jurídica abaixo e retorne um objeto JSON contendo as informações extraídas.
    Siga estritamente esta estrutura JSON:
    {
      "processNumber": "Número do processo no padrão CNJ (ex: 0000000-00.0000.0.00.0000). Se não encontrar, tente identificar um formato similar ou deixe vazio",
      "title": "Um título curto e claro em português explicando o assunto (ex: 'Apresentar réplica à contestação')",
      "category": "Escolha uma destas opções exatas: 'urgente' (prazos fatais de 1 a 3 dias ou liminares), 'prazo' (outros prazos normais), 'informativo' (sem prazo, apenas ciência), 'audiencia' (marcação de audiência/julgamento)",
      "urgencyLevel": "Escolha uma destas opções exatas: 'alta' (prazos curtos ou liminares), 'media' (prazos normais de 15 dias), 'baixa' (ciência ou prazos longos)",
      "deadlineDays": "Número inteiro representando o prazo em dias (ex: 15). Se não houver prazo claro, retorne 0",
      "actionRequired": "Instruções claras e objetivas em português para o advogado tomar as providências adequadas"
    }

    Texto da publicação:
    "${content}"`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("Sem resposta do modelo Gemini.");
    }

    const parsed = JSON.parse(responseText.trim());
    
    // Calculate due date based on calculated business days
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(dateToUse, deadlineDays)
      : dateToUse.toISOString();

    return res.json({
      processNumber: parsed.processNumber || "Não identificado",
      title: parsed.title || "Publicação Jurídica",
      category: parsed.category || "informativo",
      urgencyLevel: parsed.urgencyLevel || "baixa",
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar teor da publicação.",
      content: content,
      subpoenaDate: dateToUse.toISOString()
    });

  } catch (error: any) {
    console.error("Erro na análise do Gemini:", error);
    return res.status(500).json({ error: "Erro ao processar análise da publicação com IA: " + error.message });
  }
});

// 2. API: Gmail Sync (queries Gmail using OAuth Access Token passed by frontend)
app.post("/api/gmail-sync", async (req, res) => {
  const { accessToken } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
        // 1. Fetch recent messages with legal keywords
    const query = encodeURIComponent('subject:(intimação OR "diário de justiça" OR "pje" OR processo OR prazo OR tribunal) OR "intimação jurídica"');
    const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${query}&maxResults=10`;
    
    const listResponse = await fetch(listUrl, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      }
    });

    if (!listResponse.ok) {
      const errorText = await listResponse.text();
      if (listResponse.status === 400 || listResponse.status === 401 || listResponse.status === 403 || errorText.includes("invalid_grant") || errorText.includes("authError") || errorText.includes("Invalid Credentials") || errorText.includes("invalid_token") || errorText.includes("expired")) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
      return res.status(listResponse.status).json({ error: `Erro ao listar mensagens do Gmail: ${errorText}` });
    }

    const listData = await listResponse.json() as { messages?: Array<{ id: string, threadId: string }> };
    
    if (!listData.messages || listData.messages.length === 0) {
      return res.json({ publications: [], count: 0 });
    }

    const fetchedPublications: any[] = [];

    // 2. Fetch details for the first 5 messages
    const messagesToFetch = listData.messages.slice(0, 5);

    for (const msg of messagesToFetch) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (!detailRes.ok) continue;

      const detailData = await detailRes.json() as any;
      const headers = detailData.payload?.headers || [];
      const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
      const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "Desconhecido";
      const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
      const emailDate = dateHeader ? new Date(dateHeader) : new Date();

      // Extract raw snippet or body text
      let bodyText = detailData.snippet || "";
      
      // Look for plain text parts in payload
      const parts = detailData.payload?.parts || [];
      if (parts.length > 0) {
        const textPart = parts.find((p: any) => p.mimeType === "text/plain");
        if (textPart && textPart.body?.data) {
          bodyText = Buffer.from(textPart.body.data, 'base64').toString('utf-8');
        }
      } else if (detailData.payload?.body?.data) {
        bodyText = Buffer.from(detailData.payload.body.data, 'base64').toString('utf-8');
      }

      // Truncate text for prompt token limit safety
      const textToAnalyze = `${subject}\n\nDe: ${from}\n\n${bodyText}`.slice(0, 2500);

      // 3. Process each email with Gemini to check if it represents a judicial notification or subpoena, and extract fields
      const prompt = `Analise o e-mail abaixo. Determine se ele se trata de uma notificação judicial, intimação, publicação de diário oficial ou alerta de processo (PJE). 
      Se for, extraia os dados e preencha a estrutura JSON abaixo. Se NÃO for relacionado a processo judicial ou intimação de advogado, retorne um objeto vazio {}.

      Siga estritamente esta estrutura JSON:
      {
        "processNumber": "Número do processo no formato CNJ (0000000-00.0000.0.00.0000). Se não encontrado, deixe em branco",
        "title": "Um resumo amigável em português (ex: intimação de audiência, réplica, prazo de recurso)",
        "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
        "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
        "deadlineDays": "Número de dias do prazo útil (ex: 5, 15). Se não houver prazo claro, retorne 0",
        "actionRequired": "Recomendação objetiva em português para o advogado"
      }

      Conteúdo do E-mail:
      "${textToAnalyze}"`;

      try {
        const aiResponse = await ai.models.generateContent({
          model: "gemini-3.5-flash",
          contents: prompt,
          config: {
            responseMimeType: "application/json",
          }
        });

        const textResponse = aiResponse.text;
        if (textResponse) {
          const parsed = JSON.parse(textResponse.trim());
          // If the parsed object is not empty, include it in the results
          if (parsed && (parsed.processNumber || parsed.title)) {
            const deadlineDays = parseInt(parsed.deadlineDays) || 0;
            const dueDate = deadlineDays > 0 
              ? calculateBusinessDaysDate(emailDate, deadlineDays)
              : emailDate.toISOString();

            fetchedPublications.push({
              id: `gmail-${msg.id}`,
              processNumber: parsed.processNumber || "Não identificado",
              title: parsed.title || `E-mail: ${subject}`,
              content: `De: ${from}\nAssunto: ${subject}\n\n${bodyText.slice(0, 800)}...`,
              source: "gmail",
              category: parsed.category || "informativo",
              urgencyLevel: parsed.urgencyLevel || "baixa",
              subpoenaDate: emailDate.toISOString(),
              deadlineDays: deadlineDays,
              dueDate: dueDate,
              actionRequired: parsed.actionRequired || "Verificar teor do e-mail recebido.",
              status: "pendente",
              createdAt: new Date().toISOString()
            });
          }
        }
      } catch (innerErr) {
        console.error(`Erro ao analisar mensagem ${msg.id} com Gemini:`, innerErr);
      }
    }

    return res.json({ publications: fetchedPublications, count: fetchedPublications.length });

  } catch (error: any) {
    if (error.status === 400 || error.status === 401 || error.status === 403 || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Invalid Credentials") || error.message?.includes("Sessão Google") || error.message?.includes("consultar o Gmail")) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    console.error("Erro ao sincronizar Gmail:", error);
    return res.status(500).json({ error: "Falha na sincronização do Gmail: " + error.message });
  }
});

// Helper function to fetch Gmail PUSH stats with full pagination support
async function fetchGmailPushStats(accessToken: string, sender: string) {
  try {
    // 1. Get total emails in inbox
    let totalCount = 0;
    let nextPageToken: string | undefined = undefined;
    let newestMessageId: string | null = null;

    const baseQuery = `in:inbox from:(${sender})`;
    
    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(baseQuery)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        const errText = await res.text();
        if (errText.includes("invalid_grant") || errText.includes("authError") || errText.includes("Invalid Credentials") || errText.includes("invalid_token") || errText.includes("expired")) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Remetente consultado: ${sender}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        if (!newestMessageId) {
          newestMessageId = data.messages[0].id;
        }
        totalCount += data.messages.length;
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    // 2. Get unread emails in inbox
    let unreadCount = 0;
    let nextUnreadPageToken: string | undefined = undefined;
    const unreadQuery = `in:inbox is:unread from:(${sender})`;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(unreadQuery)}&maxResults=500${nextUnreadPageToken ? `&pageToken=${nextUnreadPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        const errText = await res.text();
        if (errText.includes("invalid_grant") || errText.includes("authError") || errText.includes("Invalid Credentials") || errText.includes("invalid_token") || errText.includes("expired")) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Remetente consultado: ${sender}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages) {
        unreadCount += data.messages.length;
      }
      nextUnreadPageToken = data.nextPageToken;
    } while (nextUnreadPageToken);

    // 3. Get details of the newest message if exists
    let newestSubject = "Nenhum e-mail recente";
    let newestDate: string | null = null;

    if (newestMessageId) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMessageId}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (detailRes.ok) {
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        newestSubject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        newestDate = dateHeader ? new Date(dateHeader).toISOString() : null;
      }
    }

    return {
      sender,
      totalCount,
      unreadCount,
      newestSubject,
      newestDate,
      success: true
    };

  } catch (error: any) {
    if (error.status === 400 || error.status === 401 || error.status === 403 || error.message === "UNAUTHENTICATED" || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Sessão Google") || error.message?.includes("consultar o Gmail")) {
      console.warn(`[Gmail] Token inválido ou expirado para consulta: ${sender}`);
      return {
        sender,
        totalCount: 0,
        unreadCount: 0,
        newestSubject: "Sessão expirada",
        newestDate: null,
        success: false,
        unauthenticated: true,
        error: "Sessão Google expirada ou inválida."
      };
    }
    console.error(`Erro ao buscar estatísticas do PUSH para ${sender}:`, error);
    return {
      sender,
      totalCount: 0,
      unreadCount: 0,
      newestSubject: "Erro de consulta",
      newestDate: null,
      success: false,
      error: error.message || "Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente."
    };
  }
}

// 2.5 API: Gmail Pushes statistics (queries counts and latest push info for courtroom systems)
app.post("/api/gmail-pushes", async (req, res) => {
  const { accessToken, sender } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  const PUSH_SOURCES = [
    { id: "trt-mg", name: "Push TRT-MG", sender: "nao-responda@trt3.jus.br" },
    { id: "pje-mg", name: "Push – PJe MG", sender: "pje@tjmg.jus.br" },
    { id: "tjmg", name: "Push TJMG", sender: "push@tjmg.jus.br" },
    { id: "eproc-tjmg", name: "Push Eproc TJMG", sender: "noreply@tjmg.jus.br" },
    { id: "trf6", name: "Eproc – Push TRF6", sender: "eproc@trf6.jus.br" }
  ];

  try {
    if (sender) {
      const stats = await fetchGmailPushStats(accessToken, sender);
      if (stats.unauthenticated) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
      return res.json({ stats: [stats] });
    } else {
      const promises = PUSH_SOURCES.map(source => fetchGmailPushStats(accessToken, source.sender));
      const results = await Promise.all(promises);
      if (results.some(r => r.unauthenticated)) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
      return res.json({ stats: results });
    }
  } catch (error: any) {
    if (error.status === 401 || error.status === 403 || error.message === "UNAUTHENTICATED") {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    console.error("Erro no endpoint /api/gmail-pushes:", error);
    return res.status(500).json({ error: "Falha ao recuperar estatísticas dos PUSHes: " + error.message });
  }
});

// 2.6 API: Gmail Pushes grouped by CNJ (for the operational cleaning and checking panel)
app.post("/api/gmail-pushes/grouped-by-cnj", async (req, res) => {
  const { accessToken, sender, page = 1, limit = 50, search = "" } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!sender) {
    return res.status(400).json({ error: "Remetente do push (sender) não fornecido." });
  }

  try {
    let messages: Array<{ id: string, threadId: string }> = [];
    let nextPageToken: string | undefined = undefined;
    let q = `in:inbox from:(${sender})`;
    if (search && search.trim() !== "") {
      q += ` "${search.trim()}"`;
    }

    let pageCount = 0;
    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(q)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const apiRes = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      if (!apiRes.ok) {
        if (apiRes.status === 400 || apiRes.status === 401 || apiRes.status === 403) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = apiRes.status;
          throw authErr;
        }
        const errText = await apiRes.text();
        if (errText.includes("invalid_grant") || errText.includes("authError") || errText.includes("Invalid Credentials") || errText.includes("invalid_token") || errText.includes("expired")) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = apiRes.status;
          throw authErr;
        }
        throw new Error(`Erro ao listar mensagens do Gmail: ${errText}`);
      }
      const data = await apiRes.json() as any;
      if (data.messages) {
        messages = messages.concat(data.messages);
      }
      nextPageToken = data.nextPageToken;
      pageCount++;
    } while (nextPageToken && pageCount < 3); // limit to 1500 messages max to prevent timeout

    const totalEmails = messages.length;

    // Fetch details for all messages with concurrency control (up to 40 parallel requests)
    const msgDetails = await fetchWithConcurrency(messages, 40, async (msg) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        if (!detailRes.ok) return null;
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();
        const snippet = detailData.snippet || "";
        const labelIds = detailData.labelIds || [];
        const isUnread = labelIds.includes("UNREAD");

        return {
          id: msg.id,
          threadId: msg.threadId,
          subject,
          snippet,
          date: emailDate,
          isUnread
        };
      } catch (err) {
        console.error(`Erro ao buscar detalhes da mensagem ${msg.id}:`, err);
        return null;
      }
    });

    const validDetails = msgDetails.filter((m): m is any => m !== null);

    // Filter out messages that don't have CNJs in subject or snippet, to fetch bodyText and try finding CNJ there
    const messagesWithoutCnj = validDetails.filter(m => {
      const subjectCnjs = extractCNJsFromText(m.subject);
      const snippetCnjs = extractCNJsFromText(m.snippet);
      return subjectCnjs.length === 0 && snippetCnjs.length === 0;
    });

    // Fetch full format only for up to 30 messages without CNJ to avoid rate limiting
    const bodyFetchedMsgs = await fetchWithConcurrency(messagesWithoutCnj.slice(0, 30), 15, async (msg) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${msg.id}?format=full`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });
        if (!detailRes.ok) return null;
        const detailData = await detailRes.json() as any;
        
        let bodyText = detailData.snippet || "";
        const parts = detailData.payload?.parts || [];
        if (parts.length > 0) {
          const textPart = parts.find((p: any) => p.mimeType === "text/plain");
          if (textPart && textPart.body?.data) {
            bodyText = Buffer.from(textPart.body.data, 'base64').toString('utf-8');
          }
        } else if (detailData.payload?.body?.data) {
          bodyText = Buffer.from(detailData.payload.body.data, 'base64').toString('utf-8');
        }
        
        return {
          id: msg.id,
          bodyText
        };
      } catch (err) {
        return null;
      }
    });

    const bodyTextMap = new Map<string, string>();
    for (const b of bodyFetchedMsgs) {
      if (b) bodyTextMap.set(b.id, b.bodyText);
    }

    // Now process and extract all CNJs
    const processedMessages = validDetails.map(msg => {
      let cnjs = Array.from(new Set([
        ...extractCNJsFromText(msg.subject),
        ...extractCNJsFromText(msg.snippet)
      ]));

      if (cnjs.length === 0) {
        const bodyText = bodyTextMap.get(msg.id);
        if (bodyText) {
          cnjs = extractCNJsFromText(bodyText);
        }
      }

      return {
        ...msg,
        cnjs
      };
    });

    // Grouping by CNJ
    // Key: CNJ number, or "Não identificado"
    const cnjGroupsMap = new Map<string, any>();
    const unassignedGroup: any[] = [];

    // Helper to get Source ID from sender email
    const PUSH_SOURCES_MAP = [
      { id: "trt-mg", sender: "nao-responda@trt3.jus.br" },
      { id: "pje-mg", sender: "pje@tjmg.jus.br" },
      { id: "tjmg", sender: "push@tjmg.jus.br" },
      { id: "eproc-tjmg", sender: "noreply@tjmg.jus.br" },
      { id: "trf6", sender: "eproc@trf6.jus.br" }
    ];
    const sourceId = PUSH_SOURCES_MAP.find(s => s.sender === sender)?.id || "trt-mg";

    for (const msg of processedMessages) {
      if (msg.cnjs.length === 0) {
        unassignedGroup.push(msg);
      } else {
        for (const cnj of msg.cnjs) {
          if (!cnjGroupsMap.has(cnj)) {
            cnjGroupsMap.set(cnj, {
              processNumber: cnj,
              messages: [],
              totalCount: 0,
              unreadCount: 0,
              latestSubject: "",
              latestDate: ""
            });
          }
          const group = cnjGroupsMap.get(cnj);
          group.messages.push(msg);
        }
      }
    }

    // Finalize groups
    const groupsList: any[] = [];
    for (const [cnj, group] of cnjGroupsMap.entries()) {
      // Sort messages in group by date descending to get the latest subject/date
      group.messages.sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime());
      
      const unreadCount = group.messages.filter((m: any) => m.isUnread).length;
      const latestMessage = group.messages[0];

      // Build URLs
      const gmailSearchUrl = `https://mail.google.com/mail/u/0/#search/in%3Ainbox+from%3A${encodeURIComponent(sender)}+%22${encodeURIComponent(cnj)}%22`;
      const todoistUrl = `https://app.todoist.com/app/search/${encodeURIComponent(cnj)}?intent=searchCompleted`;
      
      let courtSearchUrl = `https://pje.trt3.jus.br/consultaprocessual/detalhe-processo/${cnj}`;
      if (sourceId === "pje-mg" || sourceId === "tjmg") {
        courtSearchUrl = "https://pje.tjmg.jus.br/pje/ConsultaPublica/listView.seam";
      } else if (sourceId === "eproc-tjmg") {
        courtSearchUrl = "https://eproc.tjmg.jus.br/eproc/externo_controlador.php?controle=publicacao_pesquisa";
      } else if (sourceId === "trf6") {
        courtSearchUrl = "https://eproc.trf6.jus.br/eproc/externo_controlador.php?controle=publicacao_pesquisa";
      }

      groupsList.push({
        processNumber: cnj,
        totalCount: group.messages.length,
        unreadCount,
        latestSubject: latestMessage.subject,
        latestDate: latestMessage.date,
        messageIds: group.messages.map((m: any) => m.id),
        gmailSearchUrl,
        todoistUrl,
        courtSearchUrl,
        messages: group.messages
      });
    }

    // Sort valid CNJ groups from highest email count to lowest
    groupsList.sort((a, b) => b.totalCount - a.totalCount);

    // If there are unassigned messages, append a "Não identificado" group at the end
    if (unassignedGroup.length > 0) {
      unassignedGroup.sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime());
      const unreadCount = unassignedGroup.filter((m: any) => m.isUnread).length;
      const latestMessage = unassignedGroup[0];

      groupsList.push({
        processNumber: "Não identificado",
        totalCount: unassignedGroup.length,
        unreadCount,
        latestSubject: latestMessage.subject,
        latestDate: latestMessage.date,
        messageIds: unassignedGroup.map((m: any) => m.id),
        gmailSearchUrl: `https://mail.google.com/mail/u/0/#search/in%3Ainbox+from%3A${encodeURIComponent(sender)}`,
        todoistUrl: "",
        courtSearchUrl: "",
        messages: unassignedGroup
      });
    }

    const totalProcesses = cnjGroupsMap.size;

    // Apply pagination
    const pageNum = parseInt(page as any || "1", 10);
    const limitNum = parseInt(limit as any || "50", 10);
    const startIndex = (pageNum - 1) * limitNum;
    const endIndex = pageNum * limitNum;
    const paginatedGroups = groupsList.slice(startIndex, endIndex);

    return res.json({
      sender,
      totalEmails,
      totalProcesses,
      page: pageNum,
      limit: limitNum,
      totalPages: Math.ceil(groupsList.length / limitNum),
      groups: paginatedGroups
    });

  } catch (error: any) {
    if (error.status === 400 || error.status === 401 || error.status === 403 || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Invalid Credentials") || error.message?.includes("Sessão Google") || error.message?.includes("consultar o Gmail")) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    console.error("Erro no endpoint /api/gmail-pushes/grouped-by-cnj:", error);
    return res.status(500).json({ error: "Falha ao agrupar PUSHes por CNJ: " + error.message });
  }
});

// 2.7 API: Mark Gmail messages as read in batch
app.post("/api/gmail-pushes/mark-as-read", async (req, res) => {
  const { accessToken, messageIds } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Lista de messageIds é obrigatória." });
  }

  try {
    const url = "https://gmail.googleapis.com/gmail/v1/users/me/messages/batchModify";
    const apiRes = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        ids: messageIds,
        removeLabelIds: ["UNREAD"]
      })
    });

    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Erro ao marcar mensagens como lidas: ${errText}`);
    }

    return res.json({ success: true, count: messageIds.length });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-pushes/mark-as-read:", error);
    return res.status(500).json({ error: "Falha ao marcar PUSHes como lidos: " + error.message });
  }
});

// 2.8 API: Batch modify labels (e.g. archive, mark unread/read)
app.post("/api/gmail-messages/batch-modify", async (req, res) => {
  const { accessToken, messageIds, addLabelIds = [], removeLabelIds = [] } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Lista de messageIds é obrigatória." });
  }

  try {
    const url = "https://gmail.googleapis.com/gmail/v1/users/me/messages/batchModify";
    const apiRes = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        ids: messageIds,
        addLabelIds,
        removeLabelIds
      })
    });

    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Erro ao modificar mensagens: ${errText}`);
    }

    return res.json({ success: true, count: messageIds.length });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-messages/batch-modify:", error);
    return res.status(500).json({ error: "Falha ao modificar e-mails: " + error.message });
  }
});

// 2.9 API: Batch trash/delete emails
app.post("/api/gmail-messages/batch-trash", async (req, res) => {
  const { accessToken, messageIds } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }
  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Lista de messageIds é obrigatória." });
  }

  try {
    const url = "https://gmail.googleapis.com/gmail/v1/users/me/messages/batchTrash";
    const apiRes = await fetch(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        ids: messageIds
      })
    });

    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Erro ao mover mensagens para lixeira: ${errText}`);
    }

    return res.json({ success: true, count: messageIds.length });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-messages/batch-trash:", error);
    return res.status(500).json({ error: "Falha ao lixar e-mails: " + error.message });
  }
});

// 2.10 API: Fetch global inbox and count stats
app.post("/api/gmail-global-stats", async (req, res) => {
  const { accessToken, forceRefetch } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
    const cb = forceRefetch ? `?_cb=${Date.now()}` : "";
    const headers: Record<string, string> = { 
      Authorization: `Bearer ${accessToken}`
    };
    if (forceRefetch) {
      headers["Cache-Control"] = "no-cache, no-store, must-revalidate";
      headers["Pragma"] = "no-cache";
      console.log(`[Gmail Stats] Forçando refetch com limpeza de cache. Timestamp: ${Date.now()}`);
    }

    // 1. Get profile stats (messagesTotal)
    const profileUrl = `https://gmail.googleapis.com/gmail/v1/users/me/profile${cb}`;
    const profileRes = await fetch(profileUrl, { headers });
    let messagesTotal = 15000;
    let emailAddress = "";
    if (profileRes.ok) {
      const profileData = await profileRes.json() as any;
      messagesTotal = profileData.messagesTotal || 15000;
      emailAddress = profileData.emailAddress || "";
    } else {
      const errorText = await profileRes.text();
      if (profileRes.status === 400 || profileRes.status === 401 || profileRes.status === 403 || errorText.includes("invalid_grant") || errorText.includes("authError") || errorText.includes("Invalid Credentials") || errorText.includes("invalid_token") || errorText.includes("expired")) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
    }

    // 2. Get inbox count & unread count via label lookup (fast & accurate)
    const labelInboxUrl = `https://gmail.googleapis.com/gmail/v1/users/me/labels/INBOX${cb}`;
    const labelInboxRes = await fetch(labelInboxUrl, { headers });
    
    let inboxCount = 0;
    let unreadCount = 0;
    if (labelInboxRes.ok) {
      const labelData = await labelInboxRes.json() as any;
      // Prefer threads counts (conversations) to match standard Gmail Inbox/Unread UI
      inboxCount = typeof labelData.threadsTotal === 'number' ? labelData.threadsTotal : (labelData.messagesTotal || 0);
      unreadCount = typeof labelData.threadsUnread === 'number' ? labelData.threadsUnread : (labelData.messagesUnread || 0);
    } else {
      // Fallback using threads list endpoint for accurate conversation/thread estimation
      const inboxListUrl = `https://gmail.googleapis.com/gmail/v1/users/me/threads${cb}${forceRefetch ? "&" : "?"}q=in:inbox&maxResults=1`;
      const listRes = await fetch(inboxListUrl, { headers });
      if (listRes.ok) {
        const listData = await listRes.json() as any;
        inboxCount = listData.resultSizeEstimate || 0;
      }
      const unreadListUrl = `https://gmail.googleapis.com/gmail/v1/users/me/threads${cb}${forceRefetch ? "&" : "?"}q=in:inbox is:unread&maxResults=1`;
      const unreadListRes = await fetch(unreadListUrl, { headers });
      if (unreadListRes.ok) {
        const listData = await unreadListRes.json() as any;
        unreadCount = listData.resultSizeEstimate || 0;
      }
    }

    return res.json({
      success: true,
      emailAddress,
      messagesTotal,
      inboxCount,
      unreadCount
    });
  } catch (error: any) {
    console.error("Erro no endpoint /api/gmail-global-stats:", error);
    return res.status(500).json({ error: "Falha ao obter estatísticas globais: " + error.message });
  }
});

// 3. LEGACY INTEGRATION API Endpoints
// Expose endpoint for legacy CRM/ERP to POST publications
app.post("/api/legacy/publications", async (req, res) => {
  const { token, processNumber, title, content, subpoenaDate } = req.body as LegacyPublicationInput;

  if (!token) {
    return res.status(401).json({ error: "Token de autorização da API legada é obrigatório." });
  }

  if (!validTokens.includes(token)) {
    return res.status(403).json({ error: "Token inválido ou expirado." });
  }

  if (!processNumber || !content) {
    return res.status(400).json({ error: "ProcessNumber e Content são campos obrigatórios." });
  }

  try {
    // Run AI analysis on the raw legacy text
    const prompt = `Analise o texto recebido de um sistema jurídico legado e retorne uma classificação JSON.
    Siga estritamente esta estrutura JSON:
    {
      "title": "Um resumo amigável do assunto em português",
      "category": "Escolha entre: 'urgente', 'prazo', 'informativo', 'audiencia'",
      "urgencyLevel": "Escolha entre: 'alta', 'media', 'baixa'",
      "deadlineDays": "Prazo em dias (inteiro). Se não identificado, use 0",
      "actionRequired": "Recomendação de providência para o advogado"
    }

    Texto:
    "${content}"`;

    const aiRes = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      }
    });

    const aiText = aiRes.text;
    const parsed = aiText ? JSON.parse(aiText.trim()) : {};

    const rawDate = subpoenaDate ? new Date(subpoenaDate) : new Date();
    const deadlineDays = parseInt(parsed.deadlineDays) || 0;
    const dueDate = deadlineDays > 0 
      ? calculateBusinessDaysDate(rawDate, deadlineDays)
      : rawDate.toISOString();

    const newLegacyPub = {
      id: `legacy-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      processNumber: processNumber,
      title: title || parsed.title || "Intimação Recebida via API",
      content: content,
      source: "legacy_api",
      category: parsed.category || "prazo",
      urgencyLevel: parsed.urgencyLevel || "media",
      subpoenaDate: rawDate.toISOString(),
      deadlineDays: deadlineDays,
      dueDate: dueDate,
      actionRequired: parsed.actionRequired || "Verificar publicação integrada via API.",
      status: "pendente",
      createdAt: new Date().toISOString()
    };

    legacyPublicationsPool.unshift(newLegacyPub);

    return res.json({
      success: true,
      message: "Publicação recebida e analisada com IA com sucesso.",
      publication: newLegacyPub
    });

  } catch (error: any) {
    console.error("Erro no processamento da API legada:", error);
    return res.status(500).json({ error: "Falha ao processar postagem da API legada: " + error.message });
  }
});

// Endpoint to list all publications received from legacy API
app.get("/api/legacy/publications", (req, res) => {
  return res.json({ publications: legacyPublicationsPool });
});

// Endpoint to generate/register a new API Token
app.post("/api/legacy/tokens", (req, res) => {
  const { name } = req.body;
  if (!name) {
    return res.status(400).json({ error: "Nome do sistema integrado é obrigatório." });
  }
  const newToken = `BOSS_API_TOKEN_${Math.random().toString(36).substring(2, 15).toUpperCase()}`;
  validTokens.push(newToken);
  return res.json({ token: newToken, name: name, createdAt: new Date().toISOString() });
});

// Helper function to fetch Gmail stats for a custom search query with full pagination
async function fetchGmailStatsForQuery(accessToken: string, queryStr: string) {
  try {
    let totalCount = 0;
    let nextPageToken: string | undefined = undefined;
    let newestMessageId: string | null = null;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(queryStr)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        const errText = await res.text();
        if (errText.includes("invalid_grant") || errText.includes("authError") || errText.includes("Invalid Credentials") || errText.includes("invalid_token") || errText.includes("expired")) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Consulta realizada: ${queryStr}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        if (!newestMessageId) {
          newestMessageId = data.messages[0].id;
        }
        totalCount += data.messages.length;
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    let unreadQuery = queryStr;
    if (!queryStr.includes("is:unread") && !queryStr.includes("is:read")) {
      unreadQuery = `(${queryStr}) is:unread`;
    }

    let unreadCount = 0;
    let nextUnreadPageToken: string | undefined = undefined;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(unreadQuery)}&maxResults=500${nextUnreadPageToken ? `&pageToken=${nextUnreadPageToken}` : ''}`;
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });
      
      if (!res.ok) {
        if (res.status === 400 || res.status === 401 || res.status === 403) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        const errText = await res.text();
        if (errText.includes("invalid_grant") || errText.includes("authError") || errText.includes("Invalid Credentials") || errText.includes("invalid_token") || errText.includes("expired")) {
          const authErr = new Error("UNAUTHENTICATED");
          (authErr as any).status = res.status;
          throw authErr;
        }
        console.error(`[Gmail Technical Log] URL chamada: ${url} | Status HTTP: ${res.status} | Mensagem do erro: ${errText} | Consulta realizada: ${unreadQuery}`);
        throw new Error("Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente.");
      }
      
      const data = await res.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages) {
        unreadCount += data.messages.length;
      }
      nextUnreadPageToken = data.nextPageToken;
    } while (nextUnreadPageToken);

    let newestSubject = "Nenhum e-mail recente";
    let newestDate: string | null = null;

    if (newestMessageId) {
      const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMessageId}?format=metadata&metadataHeaders=subject&metadataHeaders=date`;
      const detailRes = await fetch(detailUrl, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (detailRes.ok) {
        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        newestSubject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value;
        newestDate = dateHeader ? new Date(dateHeader).toISOString() : null;
      }
    }

    return {
      query: queryStr,
      totalCount,
      unreadCount,
      newestSubject,
      newestDate,
      success: true
    };
  } catch (error: any) {
    if (error.status === 400 || error.status === 401 || error.status === 403 || error.message === "UNAUTHENTICATED" || error.message?.includes("Invalid Credentials") || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Sessão Google") || error.message?.includes("consultar o Gmail")) {
      console.warn(`[Gmail] Token inválido ou expirado para consulta: ${queryStr}`);
      return {
        query: queryStr,
        totalCount: 0,
        unreadCount: 0,
        newestSubject: "Sessão expirada",
        newestDate: null,
        success: false,
        unauthenticated: true,
        error: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente."
      };
    }
    console.error(`Erro ao buscar estatísticas do Gmail para query (${queryStr}):`, error);
    return {
      query: queryStr,
      totalCount: 0,
      unreadCount: 0,
      newestSubject: "Erro de consulta",
      newestDate: null,
      success: false,
      error: error.message || "Não foi possível consultar o Gmail. Verifique se a sessão Google está ativa e tente atualizar novamente."
    };
  }
}

// Helper to recursively traverse email parts and extract text/plain and text/html
function getEmailBody(payload: any): { text: string; html: string } {
  let text = '';
  let html = '';

  function traverse(part: any) {
    if (!part) return;
    if (part.mimeType === 'text/plain' && part.body?.data) {
      text += Buffer.from(part.body.data, 'base64').toString('utf-8');
    } else if (part.mimeType === 'text/html' && part.body?.data) {
      html += Buffer.from(part.body.data, 'base64').toString('utf-8');
    }
    if (part.parts) {
      for (const subPart of part.parts) {
        traverse(subPart);
      }
    }
  }

  traverse(payload);
  return { text, html };
}

// Helper to convert HTML to standard plain text, preserving structure
function htmlToPlainText(html: string): string {
  if (!html) return '';
  let text = html
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<\/div>/gi, '\n')
    .replace(/<\/p>/gi, '\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<\/tr>/gi, '\n')
    .replace(/<\/li>/gi, '\n')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/gi, ' ')
    .replace(/&middot;/gi, '•')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&aacute;/gi, 'á').replace(/&eacute;/gi, 'é').replace(/&iacute;/gi, 'í').replace(/&oacute;/gi, 'ó').replace(/&uacute;/gi, 'ú')
    .replace(/&atilde;/gi, 'ã').replace(/&otilde;/gi, 'õ').replace(/&ccedil;/gi, 'ç').replace(/&acirc;/gi, 'â').replace(/&ecirc;/gi, 'ê')
    .replace(/&ocirc;/gi, 'ô')
    .replace(/&Agrave;/gi, 'À').replace(/&Aacute;/gi, 'Á').replace(/&Eacute;/gi, 'É').replace(/&Iacute;/gi, 'Í').replace(/&Oacute;/gi, 'Ó').replace(/&Uacute;/gi, 'Ú')
    .replace(/&Atilde;/gi, 'Ã').replace(/&Otilde;/gi, 'Õ').replace(/&Ccedil;/gi, 'Ç');
  
  return text.split('\n').map(line => line.trim()).filter(line => line.length > 0).join('\n');
}

// Extract a valid CJN Brazilian case format
function extractCNJ(text: string): string | null {
  const regex = /\b\d{7}[-.\s]?\d{2}[-.\s]?\d{4}[-.\s]?\d[-.\s]?\d{2}[-.\s]?\d{4}\b/;
  const match = text.match(regex);
  if (match) {
    let raw = match[0].replace(/[-.\s]/g, '');
    if (raw.length === 20) {
      return `${raw.slice(0, 7)}-${raw.slice(7, 9)}.${raw.slice(9, 13)}.${raw.slice(13, 14)}.${raw.slice(14, 16)}.${raw.slice(16, 20)}`;
    }
    return match[0];
  }
  return null;
}

// Split email body into individual publication blocks
function splitEmailIntoPublications(plainText: string): string[] {
  // Pattern 1: Prius explicit indices "Processo X de Y" or "Processo X/Y" or "Recorte Eletrônico Processo X de Y"
  const priusRegex = /(?:PRIUS\s+Informador\s+Jurídico\s+-\s+)?(?:Recorte\s+Eletrônico\s+)?Processo\s+(\d+)\s+de\s+(\d+)/gi;
  const priusMatches: number[] = [];
  let m;
  while ((m = priusRegex.exec(plainText)) !== null) {
    priusMatches.push(m.index);
  }

  if (priusMatches.length > 1) {
    const blocks: string[] = [];
    for (let i = 0; i < priusMatches.length; i++) {
      const start = priusMatches[i];
      const end = (i + 1 < priusMatches.length) ? priusMatches[i + 1] : plainText.length;
      blocks.push(plainText.slice(start, end).trim());
    }
    return blocks;
  }

  // Pattern 2: Split by CNJs if there are multiple CNJs found
  const cnjRegex = /\b\d{7}[-.\s]?\d{2}[-.\s]?\d{4}[-.\s]?\d[-.\s]?\d{2}[-.\s]?\d{4}\b/g;
  const cnjMatches: { index: number; cnj: string }[] = [];
  let cMatch;
  while ((cMatch = cnjRegex.exec(plainText)) !== null) {
    cnjMatches.push({ index: cMatch.index, cnj: cMatch[0] });
  }

  if (cnjMatches.length > 1) {
    const blocks: string[] = [];
    for (let i = 0; i < cnjMatches.length; i++) {
      const prevEnd = i > 0 ? cnjMatches[i - 1].index : 0;
      let start = cnjMatches[i].index;
      let walk = start;
      const walkLimit = Math.max(prevEnd, start - 200);
      while (walk > walkLimit) {
        if (plainText[walk] === '\n' && (walk === start - 1 || plainText[walk - 1] === '\n')) {
          start = walk + 1;
          break;
        }
        walk--;
      }
      if (walk === walkLimit) {
        start = walkLimit;
      }

      const nextStart = (i + 1 < cnjMatches.length) ? cnjMatches[i + 1].index : plainText.length;
      let end = nextStart;
      let nextWalk = nextStart;
      const nextWalkLimit = Math.max(start, nextStart - 200);
      while (nextWalk > nextWalkLimit) {
        if (plainText[nextWalk] === '\n' && (nextWalk === nextStart - 1 || plainText[nextWalk - 1] === '\n')) {
          end = nextWalk;
          break;
        }
        nextWalk--;
      }

      blocks.push(plainText.slice(start, end).trim());
    }
    return blocks;
  }

  // Fallback: whole text
  return [plainText];
}

// Parse metadata elements from single publication block
function parseMetadataFromBlock(blockText: string) {
  const getField = (regex: RegExp) => {
    const match = blockText.match(regex);
    return match ? match[1].trim() : "";
  };

  const cnj = extractCNJ(blockText);
  const tribunal = getField(/(?:Tribunal|TJ|TRT|TRF|Corte):\s*([^\n]+)/i) || 
                   getField(/\b(TJ[A-Z]{2}|TRT\d{1,2}|TRF\d|STF|STJ)\b/i) || "Tribunal não identificado";
  
  const diario = getField(/(?:Diário|DJO|DJE|DEJT|Diário Eletrônico):\s*([^\n]+)/i);
  const orgao = getField(/(?:Órgão|Secretaria|Vara|Juízo|Órgão Julgador|Juizado):\s*([^\n]+)/i);
  const dataPublicacao = getField(/(?:Data\s+da\s+)?Publicação:\s*(\d{2}\/\d{2}\/\d{4})/i) || getField(/Publicado\s+em\s*(\d{2}\/\d{2}\/\d{4})/i);
  const dataDivulgacao = getField(/(?:Data\s+da\s+)?Divulgação:\s*(\d{2}\/\d{2}\/\d{4})/i) || getField(/Divulgado\s+em\s*(\d{2}\/\d{2}\/\d{4})/i);
  const cliente = getField(/(?:Cliente|Interessado|Assistido):\s*([^\n]+)/i);
  const variacao = getField(/(?:Variação|Termo\s+de\s+pesquisa|Termo\s+localizado|Termo):\s*([^\n]+)/i);
  const classe = getField(/(?:Classe|Procedimento):\s*([^\n]+)/i);
  const tipoComunicacao = getField(/(?:Tipo\s+de\s+comunicação|Tipo\s+comunicação|Tipo):\s*([^\n]+)/i);
  const meio = getField(/(?:Meio):\s*([^\n]+)/i);
  const comunicacaoId = getField(/(?:Comunicação\s*ID|ID\s+da\s+comunicação|ID):\s*([^\n]+)/i);
  
  const linkMatch = blockText.match(/(https?:\/\/[^\s"'>]+)/);
  const linkInteiroTeor = linkMatch ? linkMatch[1] : "";

  let partes = "";
  const partesMatch = blockText.match(/(?:Partes|Pólo\s+Ativo|Pólo\s+Passivo|Autor\/Réu|Advogado\(s\)|Advogados):\s*([\s\S]*?)(?=\n\n|\n[A-Z][a-z]+:|$)/i);
  if (partesMatch) {
    partes = partesMatch[1].trim();
  }

  return {
    cnj,
    tribunal,
    diario,
    orgao,
    dataPublicacao,
    dataDivulgacao,
    cliente,
    variacao,
    classe,
    tipoComunicacao,
    meio,
    comunicacaoId,
    linkInteiroTeor,
    partes
  };
}

// Real Prius Conferidor Sync Endpoint
app.post("/api/prius/conferidor/sync", async (req, res) => {
  const { accessToken } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }

  try {
    // Search for Prius emails in the inbox
    const queryStr = `(from:(prius@recortediario.com.br) OR from:(prius@prius.adv.br) OR subject:("PRIUS - Publicações") OR "PRIUS")`;
    const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(queryStr)}&maxResults=5`;
    const listRes = await fetch(listUrl, {
      headers: { Authorization: `Bearer ${accessToken}` }
    });

    if (!listRes.ok) {
      if (listRes.status === 401 || listRes.status === 403) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
      const errText = await listRes.text();
      throw new Error(`Erro ao buscar e-mails Prius: ${errText}`);
    }

    const listData = await listRes.json() as any;
    if (!listData.messages || listData.messages.length === 0) {
      return res.json({
        source: "prius",
        emailSubject: "Nenhum e-mail recente localizado",
        gmailMessageId: "",
        totalDetected: 0,
        totalUnique: 0,
        totalDuplicated: 0,
        publications: []
      });
    }

    // Fetch details of the newest message
    const newestMsgId = listData.messages[0].id;
    const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMsgId}?format=full`;
    const detailRes = await fetch(detailUrl, {
      headers: { Authorization: `Bearer ${accessToken}` }
    });

    if (!detailRes.ok) {
      throw new Error(`Erro ao detalhar e-mail Prius: ${await detailRes.text()}`);
    }

    const msgDetail = await detailRes.json() as any;
    const headers = msgDetail.payload?.headers || [];
    const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "PRIUS - Publicações";
    const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "prius@recortediario.com.br";
    const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
    const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();

    const bodyContent = getEmailBody(msgDetail.payload);
    let plainText = bodyContent.text;
    if (!plainText && bodyContent.html) {
      plainText = htmlToPlainText(bodyContent.html);
    }
    if (!plainText) {
      plainText = msgDetail.snippet || "";
    }

    const rawBlocks = splitEmailIntoPublications(plainText);
    const parsedPubs: any[] = [];
    
    rawBlocks.forEach((block, idx) => {
      if (!block || block.trim().length < 15) return;
      const meta = parseMetadataFromBlock(block);
      
      parsedPubs.push({
        id: `prius-${newestMsgId}-${idx}`,
        index: idx + 1,
        total: rawBlocks.length,
        dataPublicacao: meta.dataPublicacao || new Date(emailDate).toLocaleDateString('pt-BR'),
        dataDivulgacao: meta.dataDivulgacao || new Date(emailDate).toLocaleDateString('pt-BR'),
        tribunal: meta.tribunal || "Tribunal não identificado",
        cnj: meta.cnj || "CNJ não identificado",
        cliente: meta.cliente || "Cliente não informado",
        variacao: meta.variacao || "",
        diario: meta.diario || "",
        orgao: meta.orgao || "",
        content: block,
        linkInteiroTeor: meta.linkInteiroTeor || "",
        partes: meta.partes || "",
        classe: meta.classe || "",
        tipoComunicacao: meta.tipoComunicacao || "",
        meio: meta.meio || "",
        comunicacaoId: meta.comunicacaoId || "",
        textClean: block.replace(/\r\n/g, '\n').replace(/\n+/g, '\n').trim(),
        emailSource: from,
        gmailMessageId: newestMsgId,
        status: "Pendente"
      });
    });

    const uniquePubs: any[] = [];
    const seenKeys = new Set<string>();
    let totalDuplicated = 0;

    for (const pub of parsedPubs) {
      let dupKey = "";
      if (pub.comunicacaoId) {
        dupKey = `id-${pub.comunicacaoId}`;
      } else {
        const normCnj = (pub.cnj || "").replace(/\D/g, "");
        const normContent = (pub.content || "").toLowerCase().replace(/\s+/g, "").slice(0, 200);
        dupKey = `cnj-${normCnj}-${pub.dataPublicacao}-${normContent}`;
      }

      if (seenKeys.has(dupKey)) {
        pub.status = "Duplicada";
        pub.isDuplicate = true;
        totalDuplicated++;
      } else {
        seenKeys.add(dupKey);
        pub.isDuplicate = false;
      }
      uniquePubs.push(pub);
    }

    return res.json({
      source: "prius",
      emailSubject: subject,
      gmailMessageId: newestMsgId,
      totalDetected: parsedPubs.length,
      totalUnique: parsedPubs.length - totalDuplicated,
      totalDuplicated,
      publications: uniquePubs
    });

  } catch (error: any) {
    console.error("Erro no conferidor Prius sync:", error);
    return res.status(500).json({ error: "Falha ao processar o Conferidor Prius: " + error.message });
  }
});

// Real Recorte Digital Conferidor Sync Endpoint
app.post("/api/recorte-digital/conferidor/sync", async (req, res) => {
  const { accessToken, serviceId } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }
  if (!serviceId) {
    return res.status(400).json({ error: "Service ID do Recorte Digital não fornecido." });
  }

  try {
    let queryStr = "";
    if (serviceId === 'oab-mg') {
      queryStr = `in:inbox ("Recorte Digital" "OAB/MG")`;
    } else if (serviceId === 'rj') {
      queryStr = `in:inbox ("Recorte Digital" "RJ")`;
    } else if (serviceId === 'ceara') {
      queryStr = `in:inbox ("Recorte Digital" "Ceará")`;
    } else if (serviceId === 'sao-paulo') {
      queryStr = `in:inbox ("Recorte Digital" "São Paulo")`;
    } else {
      queryStr = `in:inbox ("Recorte Digital" "${serviceId}")`;
    }

    const listUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(queryStr)}&maxResults=5`;
    const listRes = await fetch(listUrl, {
      headers: { Authorization: `Bearer ${accessToken}` }
    });

    if (!listRes.ok) {
      if (listRes.status === 401 || listRes.status === 403) {
        return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
      }
      const errText = await listRes.text();
      throw new Error(`Erro ao buscar e-mails do Recorte Digital: ${errText}`);
    }

    const listData = await listRes.json() as any;
    if (!listData.messages || listData.messages.length === 0) {
      return res.json({
        source: "recorte-digital",
        emailSubject: "Nenhum e-mail recente localizado",
        gmailMessageId: "",
        totalDetected: 0,
        totalUnique: 0,
        totalDuplicated: 0,
        publications: []
      });
    }

    const newestMsgId = listData.messages[0].id;
    const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${newestMsgId}?format=full`;
    const detailRes = await fetch(detailUrl, {
      headers: { Authorization: `Bearer ${accessToken}` }
    });

    if (!detailRes.ok) {
      throw new Error(`Erro ao detalhar e-mail Recorte Digital: ${await detailRes.text()}`);
    }

    const msgDetail = await detailRes.json() as any;
    const headers = msgDetail.payload?.headers || [];
    const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || `Recorte Digital - ${serviceId}`;
    const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "recortedigital@tjrj.jus.br";
    const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
    const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();

    const bodyContent = getEmailBody(msgDetail.payload);
    let plainText = bodyContent.text;
    if (!plainText && bodyContent.html) {
      plainText = htmlToPlainText(bodyContent.html);
    }
    if (!plainText) {
      plainText = msgDetail.snippet || "";
    }

    const rawBlocks = splitEmailIntoPublications(plainText);
    const parsedPubs: any[] = [];
    
    rawBlocks.forEach((block, idx) => {
      if (!block || block.trim().length < 15) return;
      const meta = parseMetadataFromBlock(block);
      
      parsedPubs.push({
        id: `recorte-${serviceId}-${newestMsgId}-${idx}`,
        index: idx + 1,
        total: rawBlocks.length,
        dataPublicacao: meta.dataPublicacao || new Date(emailDate).toLocaleDateString('pt-BR'),
        dataDivulgacao: meta.dataDivulgacao || new Date(emailDate).toLocaleDateString('pt-BR'),
        tribunal: meta.tribunal || (serviceId === 'rj' ? "TJRJ" : serviceId === 'ceara' ? "TJCE" : serviceId === 'sao-paulo' ? "TJSP" : serviceId === 'oab-mg' ? "TJMG" : "Tribunal não identificado"),
        cnj: meta.cnj || "CNJ não identificado",
        cliente: meta.cliente || "Cliente não informado",
        variacao: meta.variacao || "",
        diario: meta.diario || "",
        orgao: meta.orgao || "",
        content: block,
        linkInteiroTeor: meta.linkInteiroTeor || "",
        partes: meta.partes || "",
        classe: meta.classe || "",
        tipoComunicacao: meta.tipoComunicacao || "",
        meio: meta.meio || "",
        comunicacaoId: meta.comunicacaoId || "",
        textClean: block.replace(/\r\n/g, '\n').replace(/\n+/g, '\n').trim(),
        emailSource: from,
        gmailMessageId: newestMsgId,
        status: "Pendente"
      });
    });

    const uniquePubs: any[] = [];
    const seenKeys = new Set<string>();
    let totalDuplicated = 0;

    for (const pub of parsedPubs) {
      let dupKey = "";
      if (pub.comunicacaoId) {
        dupKey = `id-${pub.comunicacaoId}`;
      } else {
        const normCnj = (pub.cnj || "").replace(/\D/g, "");
        const normContent = (pub.content || "").toLowerCase().replace(/\s+/g, "").slice(0, 200);
        dupKey = `cnj-${normCnj}-${pub.dataPublicacao}-${normContent}`;
      }

      if (seenKeys.has(dupKey)) {
        pub.status = "Duplicada";
        pub.isDuplicate = true;
        totalDuplicated++;
      } else {
        seenKeys.add(dupKey);
        pub.isDuplicate = false;
      }
      uniquePubs.push(pub);
    }

    return res.json({
      source: "recorte-digital",
      emailSubject: subject,
      gmailMessageId: newestMsgId,
      totalDetected: parsedPubs.length,
      totalUnique: parsedPubs.length - totalDuplicated,
      totalDuplicated,
      publications: uniquePubs
    });

  } catch (error: any) {
    console.error("Erro no conferidor Recorte Digital sync:", error);
    return res.status(500).json({ error: "Falha ao processar o Conferidor Recorte Digital: " + error.message });
  }
});

// Prius Integration Real-check Endpoint
app.post("/api/prius/sync", async (req, res) => {
  const { accessToken } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }

  try {
    const queryStr = `in:inbox (from:(prius) OR subject:(prius) OR "PRIUS")`;
    const stats = await fetchGmailStatsForQuery(accessToken, queryStr);
    
    if (stats.unauthenticated) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    
    if (!stats.success) {
      return res.status(500).json({ error: stats.error || "Não foi possível consultar o Gmail." });
    }

    return res.json({ 
      success: true, 
      count: stats.totalCount, 
      unreadCount: stats.unreadCount,
      newestSubject: stats.newestSubject,
      newestDate: stats.newestDate,
      error: null,
      publications: [] 
    });
  } catch (error: any) {
    console.error("Erro no sync Prius:", error);
    return res.status(500).json({ error: "Falha na varredura do Prius via Gmail: " + error.message });
  }
});

// Recorte Digital Integration Real-check Endpoint
app.post("/api/recorte-digital/sync", async (req, res) => {
  const { accessToken, serviceId } = req.body;
  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Google/Gmail não fornecido." });
  }

  if (!serviceId) {
    return res.status(400).json({ error: "Service ID não fornecido." });
  }

  try {
    // Map serviceId to its respective Gmail query
    let queryStr = "";
    if (serviceId === 'oab-mg') {
      queryStr = `in:inbox ("Recorte Digital" "OAB/MG")`;
    } else if (serviceId === 'rj') {
      queryStr = `in:inbox ("Recorte Digital" "RJ")`;
    } else if (serviceId === 'ceara') {
      queryStr = `in:inbox ("Recorte Digital" "Ceará")`;
    } else if (serviceId === 'sao-paulo') {
      queryStr = `in:inbox ("Recorte Digital" "São Paulo")`;
    } else {
      queryStr = `in:inbox ("Recorte Digital" "${serviceId}")`;
    }

    const stats = await fetchGmailStatsForQuery(accessToken, queryStr);
    
    if (stats.unauthenticated) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    
    if (!stats.success) {
      return res.status(500).json({ error: stats.error || "Não foi possível consultar o Gmail." });
    }

    return res.json({ 
      success: true, 
      count: stats.totalCount, 
      unreadCount: stats.unreadCount,
      newestSubject: stats.newestSubject,
      newestDate: stats.newestDate,
      error: null,
      publications: [] 
    });
  } catch (error: any) {
    console.error(`Erro no sync Recorte Digital (${serviceId}):`, error);
    return res.status(500).json({ error: "Falha na varredura do Recorte Digital via Gmail: " + error.message });
  }
});

// 12. API: DJEN National search (now using Comunica API/PJe)
app.post("/api/djen/search", async (req, res) => {
  const { nome, oab, uf, periodo, dataInicio, dataFim } = req.body;

  if (!nome || !oab || !uf) {
    return res.status(400).json({ error: "Nome, OAB e UF são obrigatórios." });
  }

  // Define date range
  const today = new Date();
  let start = new Date();
  let end = new Date();

  const periodoLower = (periodo || "").toLowerCase();
  if (periodoLower === 'hoje') {
    start = today;
    end = today;
  } else if (periodoLower === 'ontem') {
    const yesterday = new Date();
    yesterday.setDate(today.getDate() - 1);
    start = yesterday;
    end = yesterday;
  } else if (periodoLower === 'personalizado') {
    if (!dataInicio || !dataFim) {
      return res.status(400).json({ error: "Período personalizado exige data de início e fim." });
    }
    start = new Date(dataInicio);
    end = new Date(dataFim);
  } else {
    // Matches "ultimos X dias" or just "X"
    const matchDays = periodoLower.match(/\d+/);
    if (matchDays) {
      const days = parseInt(matchDays[0], 10);
      const startDate = new Date();
      startDate.setDate(today.getDate() - days);
      start = startDate;
      end = today;
    } else {
      start = today;
      end = today;
    }
  }

  function formatDate(date: Date): string {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
  }

  const dataInicioStr = formatDate(start);
  const dataFimStr = formatDate(end);

  try {
    const publications = await ComunicaApiService.searchCommunications({
      nome,
      oab,
      uf,
      dataInicial: dataInicioStr,
      dataFinal: dataFimStr
    });

    return res.json({
      success: true,
      publications
    });

  } catch (err: any) {
    console.error("Erro ao consultar a Comunica API/PJe:", err);
    let errMsg = "Não foi possível consultar o PJe/Comunica API automaticamente. O site comunicaapi.pje.jus.br pode estar instável.";
    let isBlocked = false;

    if (err.message === "SWAGGER_GEO_BLOCKED" || err.message === "GEO_BLOCKED" || err.message === "HTTP_403_FORBIDDEN") {
      isBlocked = true;
      errMsg = "O servidor oficial da Comunica API/PJe (comunicaapi.pje.jus.br) bloqueou o acesso temporariamente devido a restrições de localização/IP (Proteção de Geo-blocking via CloudFront). Tribunais costumam restringir conexões originadas em servidores de nuvem fora do Brasil. Por favor, utilize o botão 'Abrir Swagger/Consulta Oficial' para realizar a consulta manualmente em seu navegador.";
    } else if (
      err.code === "ENOTFOUND" || 
      err.message?.includes("getaddrinfo") || 
      err.message?.includes("fetch failed") || 
      err.cause?.message?.includes("getaddrinfo") ||
      err.cause?.message?.includes("ENOTFOUND")
    ) {
      errMsg = "O servidor oficial da Comunica API/PJe (comunicaapi.pje.jus.br) está temporariamente inacessível ou offline (Erro de Conexão/DNS). Por favor, tente novamente mais tarde ou clique em 'Abrir Swagger/Consulta Oficial'.";
    } else if (err.message) {
      errMsg = `Erro ao acessar a Comunica API/PJe: ${err.message}.`;
    }

    return res.status(200).json({
      success: false,
      blocked: isBlocked,
      error: errMsg
    });
  }
});

// Helper to decode Gmail base64
function decodeBase64(data: string): string {
  const normalized = data.replace(/-/g, '+').replace(/_/g, '/');
  return Buffer.from(normalized, 'base64').toString('utf-8');
}

// Helper to recursively parse message body parts
function cleanHtmlToText(html: string): string {
  // Remove style blocks
  let clean = html.replace(/<style[^>]*>([\s\S]*?)<\/style>/gi, "");
  // Remove script blocks
  clean = clean.replace(/<script[^>]*>([\s\S]*?)<\/script>/gi, "");
  // Remove HTML tags
  clean = clean.replace(/<[^>]*>/g, " ");
  // Decode common HTML entities
  clean = clean
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"');
  return clean;
}

function parseBodyAndAttachments(payload: any): { bodyText: string; htmlBody: string; hasAttachments: boolean; attachments: any[] } {
  let bodyText = "";
  let htmlBody = "";
  let hasAttachments = false;
  const attachments: any[] = [];

  function traverseParts(parts: any[]) {
    for (const part of parts) {
      if (part.filename && part.filename.length > 0) {
        hasAttachments = true;
        attachments.push({
          filename: part.filename,
          mimeType: part.mimeType,
          size: part.body?.size || 0,
          attachmentId: part.body?.attachmentId
        });
      }
      
      if (part.mimeType === "text/plain" && part.body?.data) {
        bodyText += decodeBase64(part.body.data);
      } else if (part.mimeType === "text/html" && part.body?.data) {
        htmlBody += decodeBase64(part.body.data);
      }

      if (part.parts) {
        traverseParts(part.parts);
      }
    }
  }

  if (payload.parts) {
    traverseParts(payload.parts);
  } else if (payload.body?.data) {
    if (payload.mimeType === "text/plain") {
      bodyText = decodeBase64(payload.body.data);
    } else if (payload.mimeType === "text/html") {
      htmlBody = decodeBase64(payload.body.data);
    }
  }

  // If we have HTML but no plain text, generate plain text by cleanly removing styles/scripts/tags
  if (htmlBody && !bodyText) {
    bodyText = cleanHtmlToText(htmlBody);
  } else if (bodyText) {
    // If we have plain text, clean up any style blocks or CSS garbage that might be inside
    bodyText = cleanHtmlToText(bodyText);
  }

  return { bodyText: bodyText.trim(), htmlBody: htmlBody.trim(), hasAttachments, attachments };
}

// Extract judicial metadata using smart rules
function extractJudicialInfo(subject: string, bodyText: string, snippet: string) {
  const fullText = `${subject}\n${snippet}\n${bodyText}`;

  // 1. CNJ standard format: 0000000-00.0000.0.00.0000
  const cnjRegex = /(\d{7})[-.\s]?(\d{2})[-.\s]?(\d{4})[-.\s]?(\d)[-.\s]?(\d{2})[-.\s]?(\d{4})/g;
  const cnjMatches = [...fullText.matchAll(cnjRegex)];
  let processNumber = "";
  if (cnjMatches.length > 0) {
    const m = cnjMatches[0];
    processNumber = `${m[1]}-${m[2]}.${m[3]}.${m[4]}.${m[5]}.${m[6]}`;
  }

  // 2. Identify Court / Tribunal
  let tribunal = "";
  if (processNumber) {
    const parts = processNumber.split('.');
    if (parts.length >= 5) {
      const jCode = parts[3]; 
      const trCode = parts[4]; 
      if (jCode === '5' && trCode === '03') {
        tribunal = "TRT-3 (MG)";
      } else if (jCode === '8' && trCode === '13') {
        tribunal = "TJMG";
      } else if (jCode === '1' && trCode === '06') {
        tribunal = "TRF-6";
      } else {
        tribunal = `Tribunal (Código ${jCode}.${trCode})`;
      }
    }
  }

  if (!tribunal) {
    if (/trt\s?3|trt3|tribunal regional do trabalho da 3/i.test(fullText)) {
      tribunal = "TRT-3 (MG)";
    } else if (/tjmg|tribunal de justi\u00e7a de minas gerais/i.test(fullText)) {
      tribunal = "TJMG";
    } else if (/trf\s?6|trf6|tribunal regional federal da 6/i.test(fullText)) {
      tribunal = "TRF-6";
    } else if (/pje/i.test(fullText)) {
      tribunal = "PJe";
    } else if (/eproc/i.test(fullText)) {
      tribunal = "Eproc";
    } else {
      tribunal = "Não identificado";
    }
  }

  // 3. Vara
  let vara = "";
  const varaMatch = fullText.match(/(?:vara|juizado|c\u00e2mara|ju\u00edzo)\s+[^,\n.\r]{1,40}/i);
  if (varaMatch) {
    vara = varaMatch[0].trim();
  } else {
    vara = "Não identificada";
  }

  // 4. Classe processual
  let classe = "";
  const classMatch = fullText.match(/(?:classe|procedimento|tipo|a\u00e7\u00e3o):\s*([^,\n.\r]{2,40})/i);
  if (classMatch) {
    classe = classMatch[1].trim();
  } else {
    classe = "Não identificada";
  }

  // 5. Parts (Author/Defendant)
  let autor = "";
  let reu = "";
  
  const reqMatch = fullText.match(/(?:autor|reclamante|requerente|impetrante|polo ativo|recorrente):\s*([^,\n.\r]{2,50})/i);
  if (reqMatch) {
    autor = reqMatch[1].trim();
  } else {
    autor = "Não identificado";
  }

  const resMatch = fullText.match(/(?:r\u00e9u|reclamado|requerido|impetrado|polo passivo|recorrido):\s*([^,\n.\r]{2,50})/i);
  if (resMatch) {
    reu = resMatch[1].trim();
  } else {
    reu = "Não identificado";
  }

  // 6. Tipo de Movimentação
  let movementType = "";
  const movMatch = fullText.match(/(?:movimenta\u00e7\u00e3o|evento|tipo de ato|assunto):\s*([^,\n.\r]{2,60})/i);
  if (movMatch) {
    movementType = movMatch[1].trim();
  } else if (/audi\u00eancia/i.test(fullText)) {
    movementType = "Audiência Designada/Intimação";
  } else if (/senten\u00e7a|decis\u00e3o/i.test(fullText)) {
    movementType = "Sentença / Decisão Proferida";
  } else if (/despacho/i.test(fullText)) {
    movementType = "Despacho Publicado";
  } else {
    movementType = "Publicação Geral";
  }

  return {
    processNumber: processNumber || "Não identificado",
    tribunal,
    vara,
    classe,
    autor,
    reu,
    movementType
  };
}

// Endpoint to list all messages IDs from Gmail for a sender or a custom query
app.post("/api/gmail-messages-list", async (req, res) => {
  const { accessToken, sender, query: clientQuery, filter } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  try {
    let query = "";
    if (clientQuery) {
      query = clientQuery;
    } else if (sender) {
      query = `in:inbox from:(${sender})`;
    } else {
      return res.status(400).json({ error: "Sender ou Query do Gmail não fornecido." });
    }

    if (filter === 'unread' && !query.includes("is:unread") && !query.includes("is:read")) {
      query = `(${query}) is:unread`;
    }

    const messageIds: string[] = [];
    let nextPageToken: string | undefined = undefined;

    do {
      const url: string = `https://gmail.googleapis.com/gmail/v1/users/me/messages?q=${encodeURIComponent(query)}&maxResults=500${nextPageToken ? `&pageToken=${nextPageToken}` : ''}`;
      const response = await fetch(url, {
        headers: { Authorization: `Bearer ${accessToken}` }
      });

      if (!response.ok) {
        if (response.status === 401) {
          return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
        }
        const errText = await response.text();
        throw new Error(`Erro na listagem da API do Gmail: ${errText}`);
      }

      const data = await response.json() as { messages?: Array<{ id: string, threadId: string }>, nextPageToken?: string };
      if (data.messages && data.messages.length > 0) {
        data.messages.forEach(m => {
          if (m.id && !messageIds.includes(m.id)) {
            messageIds.push(m.id);
          }
        });
      }
      nextPageToken = data.nextPageToken;
    } while (nextPageToken);

    return res.json({ success: true, messageIds, totalCount: messageIds.length });
  } catch (error: any) {
    if (error.status === 401 || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Invalid Credentials")) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    console.error("Erro no endpoint /api/gmail-messages-list:", error);
    return res.status(500).json({ error: "Falha ao recuperar a lista de mensagens do Gmail: " + error.message });
  }
});

// Endpoint to get details for multiple message IDs in batch
app.post("/api/gmail-messages-details", async (req, res) => {
  const { accessToken, messageIds } = req.body;

  if (!accessToken) {
    return res.status(400).json({ error: "Access token do Gmail não fornecido." });
  }

  if (!messageIds || !Array.isArray(messageIds) || messageIds.length === 0) {
    return res.status(400).json({ error: "Array messageIds inválido ou vazio." });
  }

  try {
    const detailsPromises = messageIds.map(async (id) => {
      try {
        const detailUrl = `https://gmail.googleapis.com/gmail/v1/users/me/messages/${id}?format=full`;
        const detailRes = await fetch(detailUrl, {
          headers: { Authorization: `Bearer ${accessToken}` }
        });

        if (!detailRes.ok) {
          if (detailRes.status === 401) {
            const authErr = new Error("UNAUTHENTICATED");
            (authErr as any).status = 401;
            throw authErr;
          }
          return { id, success: false, error: `Erro HTTP ${detailRes.status}` };
        }

        const detailData = await detailRes.json() as any;
        const headers = detailData.payload?.headers || [];
        
        const subject = headers.find((h: any) => h.name.toLowerCase() === "subject")?.value || "Sem Assunto";
        const from = headers.find((h: any) => h.name.toLowerCase() === "from")?.value || "Desconhecido";
        const to = headers.find((h: any) => h.name.toLowerCase() === "to")?.value || "Desconhecido";
        const dateHeader = headers.find((h: any) => h.name.toLowerCase() === "date")?.value || "";
        const emailDate = dateHeader ? new Date(dateHeader).toISOString() : new Date().toISOString();
        const snippet = detailData.snippet || "";
        
        const labelIds = detailData.labelIds || [];
        const isUnread = labelIds.includes("UNREAD");

        const { bodyText, htmlBody, hasAttachments, attachments } = parseBodyAndAttachments(detailData.payload || {});
        
        const judicialInfo = extractJudicialInfo(subject, bodyText, snippet);

        return {
          id,
          success: true,
          subject,
          from,
          to,
          date: emailDate,
          snippet,
          isUnread,
          hasAttachments,
          attachments,
          bodyText,
          htmlBody,
          ...judicialInfo
        };
      } catch (err: any) {
        return { id, success: false, error: err.message };
      }
    });

    const results = await Promise.all(detailsPromises);
    return res.json({ success: true, messages: results });
  } catch (error: any) {
    if (error.status === 401 || error.message?.includes("UNAUTHENTICATED") || error.message?.includes("Invalid Credentials")) {
      return res.status(401).json({ error: "UNAUTHENTICATED", message: "Sessão do Google expirada ou inválida. Por favor, conecte com o Google novamente." });
    }
    console.error("Erro no endpoint /api/gmail-messages-details:", error);
    return res.status(500).json({ error: "Falha ao obter os detalhes das mensagens do Gmail: " + error.message });
  }
});

// --- TODOIST PROXY ENDPOINTS ---
app.use("/api/todoist", (req: any, res, next) => {
  const token = req.headers["x-todoist-token"] || req.headers["authorization"]?.toString().replace("Bearer ", "");
  if (!token) {
    return res.status(401).json({ error: "Token do Todoist não fornecido." });
  }
  req.todoistToken = token;
  next();
});

app.get("/api/todoist/projects", async (req: any, res) => {
  try {
    const apiRes = await fetch("https://api.todoist.com/rest/v2/projects", {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/todoist/sections", async (req: any, res) => {
  try {
    const apiRes = await fetch("https://api.todoist.com/rest/v2/sections", {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/todoist/labels", async (req: any, res) => {
  try {
    const apiRes = await fetch("https://api.todoist.com/rest/v2/labels", {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/todoist/search-all", async (req: any, res) => {
  const { cnj } = req.query;
  if (!cnj) {
    return res.status(400).json({ error: "Parâmetro cnj não fornecido." });
  }

  const cleanCnj = cnj.replace(/\s+/g, '');

  try {
    // 1. Fetch active tasks with search filter
    const activeUrl = `https://api.todoist.com/rest/v2/tasks?filter=${encodeURIComponent(`search:${cleanCnj}`)}`;
    const activeRes = await fetch(activeUrl, {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    
    let activeTasks: any[] = [];
    if (activeRes.ok) {
      activeTasks = await activeRes.json();
    }

    // 2. Fetch completed tasks (last 100) and filter by CNJ
    const completedUrl = "https://api.todoist.com/sync/v9/completed/get_all?limit=100";
    const completedRes = await fetch(completedUrl, {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });

    let completedTasks: any[] = [];
    if (completedRes.ok) {
      const completedData = await completedRes.json() as any;
      if (completedData && Array.isArray(completedData.items)) {
        completedTasks = completedData.items.filter((task: any) => {
          const content = (task.content || "").replace(/\s+/g, "");
          const description = (task.description || "").replace(/\s+/g, "");
          return content.includes(cleanCnj) || description.includes(cleanCnj);
        });
      }
    }

    // Combine them with is_completed flag properly set
    const combinedTasks = [
      ...activeTasks.map(t => ({ ...t, is_completed: false })),
      ...completedTasks.map(t => ({
        id: t.task_id || t.id,
        content: t.content,
        description: t.description || "",
        is_completed: true,
        completed_at: t.completed_at,
        project_id: t.project_id,
        labels: t.labels || [],
        priority: t.priority || 1,
        due: t.due || null,
        assignee_id: t.assignee_id || null
      }))
    ];

    // Deduplicate combinedTasks by id
    const uniqueTasksMap = new Map<string, any>();
    for (const t of combinedTasks) {
      if (t.id) {
        uniqueTasksMap.set(t.id, t);
      }
    }
    const uniqueTasks = Array.from(uniqueTasksMap.values());

    // Fetch comments for each task
    const detailsPromises = uniqueTasks.map(async (task: any) => {
      try {
        const commentsUrl = `https://api.todoist.com/rest/v2/comments?task_id=${task.id}`;
        const commentsRes = await fetch(commentsUrl, {
          headers: { Authorization: `Bearer ${req.todoistToken}` }
        });
        let comments: any[] = [];
        if (commentsRes.ok) {
          comments = await commentsRes.json();
        }
        return {
          ...task,
          comments
        };
      } catch (err) {
        return {
          ...task,
          comments: []
        };
      }
    });

    const tasksWithComments = await Promise.all(detailsPromises);
    res.json(tasksWithComments);
  } catch (err: any) {
    console.error("Erro ao buscar tarefas no Todoist:", err);
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/todoist/tasks", async (req: any, res) => {
  const { filter, project_id } = req.query;
  let url = "https://api.todoist.com/rest/v2/tasks";
  const params = new URLSearchParams();
  if (filter) params.append("filter", filter as string);
  if (project_id) params.append("project_id", project_id as string);
  if (params.toString()) url += `?${params.toString()}`;

  try {
    const apiRes = await fetch(url, {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/todoist/tasks", async (req: any, res) => {
  try {
    const apiRes = await fetch("https://api.todoist.com/rest/v2/tasks", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${req.todoistToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(req.body)
    });
    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Todoist API error: ${apiRes.status} - ${errText}`);
    }
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/todoist/tasks/:id", async (req: any, res) => {
  try {
    const apiRes = await fetch(`https://api.todoist.com/rest/v2/tasks/${req.params.id}`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${req.todoistToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(req.body)
    });
    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Todoist API error: ${apiRes.status} - ${errText}`);
    }
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.delete("/api/todoist/tasks/:id", async (req: any, res) => {
  try {
    const apiRes = await fetch(`https://api.todoist.com/rest/v2/tasks/${req.params.id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/todoist/tasks/:id/close", async (req: any, res) => {
  try {
    const apiRes = await fetch(`https://api.todoist.com/rest/v2/tasks/${req.params.id}/close`, {
      method: "POST",
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/todoist/tasks/:id/reopen", async (req: any, res) => {
  try {
    const apiRes = await fetch(`https://api.todoist.com/rest/v2/tasks/${req.params.id}/reopen`, {
      method: "POST",
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.get("/api/todoist/comments", async (req: any, res) => {
  const { task_id, project_id } = req.query;
  let url = "https://api.todoist.com/rest/v2/comments";
  if (task_id) url += `?task_id=${task_id}`;
  else if (project_id) url += `?project_id=${project_id}`;

  try {
    const apiRes = await fetch(url, {
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/todoist/comments", async (req: any, res) => {
  try {
    const apiRes = await fetch("https://api.todoist.com/rest/v2/comments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${req.todoistToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(req.body)
    });
    if (!apiRes.ok) {
      const errText = await apiRes.text();
      throw new Error(`Todoist API error: ${apiRes.status} - ${errText}`);
    }
    const data = await apiRes.json();
    res.json(data);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

app.delete("/api/todoist/comments/:id", async (req: any, res) => {
  try {
    const apiRes = await fetch(`https://api.todoist.com/rest/v2/comments/${req.params.id}`, {
      method: "DELETE",
      headers: { Authorization: `Bearer ${req.todoistToken}` }
    });
    if (!apiRes.ok) throw new Error(`Todoist API error: ${apiRes.status}`);
    res.json({ success: true });
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// Serve static build in production or mount Vite middleware in development
async function startServer() {
  if (process.env.NODE_ENV === "production") {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  } else {
    // Vite dev mode middleware
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
